import type { WeekContent } from '../types'

export const CONTENT: Record<string, WeekContent> = {
  S39: {
    title: '🚀 Accueil TP',
    bloc: 'Démarrage',
    notions: [
      'Présentation formation, équipe, outils',
      'Configuration postes, Notion, GitHub',
      'Intro IA : qu\'est-ce qui nous attend cette année ?',
    ],
    ia: 'Découverte live de Copilot et Claude',
    ia_mode: 'copilot',
    blocs_cda: [],
    fondamentaux: 'Posture de développeur, culture tech',
    links: [],
  },
  S40: {
    title: '🤖 IA théorie + Algo',
    bloc: 'Fondamentaux',
    notions: [
      'IA : histoire · LLMs · tokens · embeddings',
      'Prompt engineering · éthique · RGPD · hallucinations',
      'Algo : pseudocode · if/else · boucles · fonctions',
    ],
    ia: 'Séance fondatrice : comprendre avant d\'utiliser',
    ia_mode: 'theory',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'Logique algorithmique, pensée computationnelle',
    links: [],
  },
  S41: {
    title: '📐 Algo avancé',
    bloc: 'Fondamentaux',
    notions: [
      'Tableaux : parcours, recherche, tri basique',
      'Récursivité (introduction)',
      'Katas repo JS : tests rouges/verts',
    ],
    ia: 'Comparer sa solution avec la solution IA',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Structures de données, abstraction',
    links: [],
  },
  S42: {
    title: '🐙 Git complet',
    bloc: 'Git',
    notions: [
      'git init · add · commit · status · log',
      'Branches : branch · merge · conflits',
      'GitHub : remote · push · pull · PR · workflow équipe',
    ],
    ia: 'Git blame + log : retrouver du contexte avec l\'IA',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC03'],
    fondamentaux: 'Contrôle de version, collaboration',
    links: [
      { label: '🐙 Git & GitHub', url: 'https://www.notion.so/Git-Github-3732ae802e298081a206e7f550efe9d6' },
      { label: '1️⃣ Git local', url: 'https://www.notion.so/3732ae802e298194b9c3dc49d0ceb550' },
    ],
  },
  S43: {
    title: '🐙 Git katas + Portfolio',
    bloc: 'Git',
    notions: [
      'Scénarios Git réels : conflits, conventions',
      'Conventional commits : feat/fix/chore',
      'Portfolio repo personnel créé (fallback certif)',
    ],
    ia: 'Générer des messages de commit → évaluer leur qualité',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC03'],
    fondamentaux: 'Bonnes pratiques versioning',
    links: [
      { label: '🐙 Git & GitHub', url: 'https://www.notion.so/Git-Github-3732ae802e298081a206e7f550efe9d6' },
      { label: '1️⃣ Git local', url: 'https://www.notion.so/3732ae802e298194b9c3dc49d0ceb550' },
    ],
  },
  S44: {
    title: '🌼 JavaScript',
    bloc: 'JavaScript',
    notions: [
      'Syntaxe · variables · types · opérateurs',
      'Fonctions · tableaux · méthodes (map/filter/reduce)',
      'Objets · destructuration · spread · rest',
    ],
    ia: 'L\'IA explique les erreurs console JS',
    ia_mode: 'mixed',
    blocs_cda: ['BC01'],
    fondamentaux: 'Langage de base, manipulation de données',
    links: [
      { label: '🌼 JavaScript', url: 'https://satin-truffle-ac4.notion.site/Javascript-1d72ae802e29804596fbe823e86fa5a0' },
      { label: 'Qu\'est-ce que JS ?', url: 'https://www.notion.so/1d72ae802e298050b54df0ccebba21a5' },
      { label: 'Syntaxe & concepts', url: 'https://www.notion.so/1d72ae802e298049a83eed89d3a22e47' },
      { label: 'Variables', url: 'https://www.notion.so/1d72ae802e2980769052fff03bfee419' },
      { label: 'Types de données', url: 'https://www.notion.so/1d72ae802e29808f9a62dadf5479b520' },
    ],
  },
  S45: {
    title: '🌼 JS avancé',
    bloc: 'JavaScript',
    notions: [
      'DOM : querySelector · events · manipulation',
      'async/await · Promises · fetch API',
      'Gestion erreurs : try/catch, .catch()',
    ],
    ia: 'Déboguer du code async avec l\'IA',
    ia_mode: 'copilot',
    blocs_cda: ['BC01'],
    fondamentaux: 'Programmation asynchrone, DOM',
    links: [
      { label: '🌼 JavaScript', url: 'https://satin-truffle-ac4.notion.site/Javascript-1d72ae802e29804596fbe823e86fa5a0' },
      { label: 'Opérateurs conditionnels', url: 'https://www.notion.so/1d72ae802e2980389e60e63e3e7df3a4' },
      { label: 'Fonctions', url: 'https://www.notion.so/1d72ae802e29803584c6cb3a1a8b0466' },
      { label: 'Tableaux', url: 'https://www.notion.so/1d72ae802e2980408b7dc81d345c8d06' },
      { label: 'Méthodes des tableaux', url: 'https://www.notion.so/1d72ae802e2980808155dbef61cd293e' },
      { label: 'Boucles', url: 'https://www.notion.so/1d72ae802e2980b881d6c414ea119ec1' },
      { label: 'Objets', url: 'https://www.notion.so/1d72ae802e2980e8b3fff6f834f6b7cd' },
      { label: 'DOM', url: 'https://www.notion.so/1d72ae802e298060acc2f8e22d0915de' },
    ],
  },
  S46: {
    title: '🟦 TypeScript approfondi',
    bloc: 'TypeScript',
    notions: [
      'Types avancés : union, intersection, generics',
      'Utility types : Partial, Required, Pick, Omit',
      'Migrer un module JS → TS strict · exercices typage',
    ],
    ia: '🔒 J1-J2 sans IA — ancrer le système de types · 🤝 J3-J5 : l\'IA génère du TS typé → repérer les dérives',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'Typage statique avancé, qualité de code',
    links: [{ label: '🟦 TypeScript', url: 'https://satin-truffle-ac4.notion.site/Typescript-25d2ae802e2980a79ea5e8a48349fb33' }],
  },
  S47: {
    title: '🎯 Vision Métier + 🛡️ Angular découverte',
    bloc: 'Vision métier',
    notions: [
      'Lun–Mer : interview client · CDC · user stories · critères d\'acceptance BDD',
      'Spec e-shop ensemble — document vivant toute l\'année',
      'Jeu–Ven : Angular CLI · architecture · premier composant standalone',
    ],
    ia: '🔒 J1-J3 Vision Métier sans IA (réflexion pure, pas de béquille) · 🤝 J4-J5 : l\'IA formule des user stories → les challenger',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'Analyse des besoins, conception, architecture front',
    links: [
      { label: '🎯 Vision Métier', url: 'https://satin-truffle-ac4.notion.site/Typescript-25d2ae802e2980a79ea5e8a48349fb33' },
      { label: '🛡️ Angular', url: 'https://satin-truffle-ac4.notion.site/Angular-2092ae802e298032b6e6f8db22315706' },
    ],
  },
  S48: {
    title: '🛡️ Angular 1',
    bloc: 'Angular',
    notions: [
      '@Component · template · styles encapsulés · lifecycle hooks',
      'Data binding : interpolation, property binding, event binding',
      '@Input() · @Output() · EventEmitter · communication composants',
    ],
    ia: '🔒 J1-J2 sans IA — comprendre les mécanismes de binding · 🤝 J3-J5 : générer un composant Angular → analyser la structure produite',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'Composants UI, communication entre composants',
    links: [
      { label: '🛡️ Angular', url: 'https://satin-truffle-ac4.notion.site/Angular-2092ae802e298032b6e6f8db22315706' },
      { label: 'Les Composants', url: 'https://www.notion.so/2092ae802e298034b8bcff5ca18a33ef' },
      { label: 'Les Templates', url: 'https://www.notion.so/2092ae802e298030857de758641e5ffc' },
    ],
  },
  S49: {
    title: '🛡️ Angular 2',
    bloc: 'Angular',
    notions: [
      'Router : routes, RouterLink, ActivatedRoute, guards',
      'Formulaires réactifs : FormGroup, FormControl, Validators',
      'Validation UX et messages d\'erreur',
    ],
    ia: 'L\'IA aide à écrire les validateurs de formulaire',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'Navigation, formulaires',
    links: [
      { label: '🛡️ Angular', url: 'https://satin-truffle-ac4.notion.site/Angular-2092ae802e298032b6e6f8db22315706' },
      { label: 'Le Router', url: 'https://www.notion.so/26f2ae802e298009ac6bdda6ae01dc94' },
      { label: 'Les Formulaires', url: 'https://www.notion.so/2702ae802e298018a7e9db10423fa1d3' },
    ],
  },
  S50: {
    title: '🛡️ Angular 3',
    bloc: 'Angular',
    notions: [
      'Services : @Injectable, injection de dépendances',
      'HttpClient : GET, POST, PUT, DELETE',
      'Intercepteurs · gestion erreurs HTTP',
    ],
    ia: '🤖 IA avancée : Copilot génère des services Angular complets',
    ia_mode: 'delegation',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'Architecture services, REST client',
    links: [
      { label: '🛡️ Angular', url: 'https://satin-truffle-ac4.notion.site/Angular-2092ae802e298032b6e6f8db22315706' },
      { label: 'Input/Output', url: 'https://www.notion.so/2092ae802e298036ab8fd70a25011e8d' },
      { label: 'Output', url: 'https://www.notion.so/2092ae802e2980dba798d305d6d48998' },
      { label: 'Les Services', url: 'https://www.notion.so/2092ae802e2980b48156f021815221dd' },
      { label: 'Les requêtes HTTP', url: 'https://www.notion.so/2092ae802e2980438132eeb436479620' },
    ],
  },
  S51: {
    title: '🛡️ Angular 4',
    bloc: 'Angular',
    notions: [
      'Signals & réactivité (Angular 17+)',
      'Optimisations : OnPush, lazy loading, trackBy',
      'Tests Angular : Jasmine, TestBed, composants isolés',
    ],
    ia: 'L\'IA génère des tests Angular → évaluer la pertinence',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC03'],
    fondamentaux: 'Performance, qualité, tests',
    links: [
      { label: '🛡️ Angular', url: 'https://satin-truffle-ac4.notion.site/Angular-2092ae802e298032b6e6f8db22315706' },
      { label: 'Signals', url: 'https://www.notion.so/2622ae802e2980d496d3c155dee2b445' },
      { label: 'Optimisations', url: 'https://www.notion.so/2792ae802e29805d9e1defbab1aa96a1' },
      { label: 'Tests', url: 'https://www.notion.so/2792ae802e2980c095b8ffbc3408733b' },
    ],
  },
  S1: {
    title: '⚙️ CI/CD Angular',
    bloc: 'CI/CD',
    notions: [
      'GitHub Actions : workflow YAML, triggers',
      'Pipeline CI : lint · tests · build Angular',
      'Pipeline CD : déploiement auto · Docker Angular · nginx',
    ],
    ia: 'L\'IA génère un workflow GitHub Actions de base',
    ia_mode: 'delegation',
    blocs_cda: ['BC03'],
    fondamentaux: 'Automatisation, déploiement continu',
    links: [
      { label: '🤖 CI-CD', url: 'https://satin-truffle-ac4.notion.site/CI-CD-2862ae802e298087b982f578be8782b7' },
      { label: 'CI + Angular', url: 'https://satin-truffle-ac4.notion.site/CI-Angular-2862ae802e2980389270d94059214d69' },
      { label: 'CD + Angular', url: 'https://satin-truffle-ac4.notion.site/CD-Angular-2862ae802e29806aad19d2e25670febe' },
    ],
  },
  S2: {
    title: '☕ Java',
    bloc: 'Java',
    notions: [
      'Rappel POO : classes, héritage, interfaces (cours Notion pré-lus)',
      'Exceptions : try/catch/finally, custom exceptions, bonnes pratiques',
      'Streams API : filter · map · collect · Optional',
    ],
    ia: 'L\'IA explique les stack traces Java',
    ia_mode: 'mixed',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'Programmation objet, gestion d\'erreurs',
    links: [
      { label: '☕ Java', url: 'https://satin-truffle-ac4.notion.site/Java-1f82ae802e2980f49405d0b5c5c311c6' },
      { label: 'JDK', url: 'https://www.notion.so/1f82ae802e29806188f1fbc5a483891f' },
      { label: 'Syntaxe & algo', url: 'https://www.notion.so/1f82ae802e298032b68dfa449bcd50be' },
      { label: 'Variables', url: 'https://www.notion.so/1f82ae802e298006a308dcf3d64ebc73' },
      { label: 'POO', url: 'https://www.notion.so/1f82ae802e2980a5be16e228fb109fe7' },
    ],
  },
  S3: {
    title: '☕ Java katas + SQL intro',
    bloc: 'Java / SQL',
    notions: [
      'Java katas : Streams, lambdas, méthodes référence',
      'JUnit 5 : @Test, assertions, @BeforeEach',
      'SQL : modèle relationnel, clés primaires/étrangères, normalisation',
    ],
    ia: 'L\'IA génère des tests JUnit → vérifier la couverture',
    ia_mode: 'copilot',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'Tests unitaires, modélisation',
    links: [
      { label: '☕ Java', url: 'https://satin-truffle-ac4.notion.site/Java-1f82ae802e2980f49405d0b5c5c311c6' },
      { label: 'POO bases', url: 'https://www.notion.so/1fa2ae802e29800ba078c4c848702b55' },
      { label: 'Héritage', url: 'https://www.notion.so/1f82ae802e2980fb8edbe864030c1284' },
      { label: 'Interfaces', url: 'https://www.notion.so/1f82ae802e2980c7ada0ed11d62b5f7c' },
      { label: 'Tableaux & itérations', url: 'https://www.notion.so/1f82ae802e2980769004f379d4443c34' },
      { label: 'ArrayList', url: 'https://www.notion.so/1f82ae802e29805ebf2ad1599ee68aee' },
    ],
  },
  S4: {
    title: '🗄️ SQL',
    bloc: 'SQL',
    notions: [
      'SELECT · WHERE · ORDER BY · LIMIT · DISTINCT',
      'JOINs : INNER · LEFT · RIGHT · FULL OUTER',
      'INSERT · UPDATE · DELETE · transactions · ROLLBACK',
    ],
    ia: 'L\'IA génère des requêtes SQL → repérer les injections potentielles',
    ia_mode: 'mixed',
    blocs_cda: ['BC02'],
    fondamentaux: 'Interrogation BDD, intégrité données',
    links: [],
  },
  S5: {
    title: '🗄️ SQL avancé',
    bloc: 'SQL',
    notions: [
      'Agrégats : COUNT · SUM · AVG · GROUP BY · HAVING',
      '🕵️ SQL Murder Mystery (exercice ludique)',
      'Schéma e-shop complet : modélisation + contraintes',
    ],
    ia: 'L\'IA explique un plan d\'exécution SQL (EXPLAIN)',
    ia_mode: 'copilot',
    blocs_cda: ['BC02'],
    fondamentaux: 'Agrégation, analyse de données',
    links: [],
  },
  S6: {
    title: '🍃 Spring Boot 1',
    bloc: 'Spring Boot',
    notions: [
      'Architecture Spring : IoC, contexte applicatif',
      'Persistance JPA : @Entity, @Repository, Spring Data',
      'Exposition REST : @RestController, CRUD endpoints',
    ],
    ia: 'L\'IA génère une entité JPA + repository → vérifier les annotations',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'Architecture N-tiers, persistance',
    links: [
      { label: '🍃 Spring Boot', url: 'https://satin-truffle-ac4.notion.site/Spring-Boot-28c2ae802e29802d9edecb8920734da3' },
      { label: 'Introduction au backend', url: 'https://www.notion.so/28d2ae802e29802b9dd8f377f61029ec' },
      { label: 'Introduction Spring Boot', url: 'https://www.notion.so/28d2ae802e298010832dee900e0bf0ab' },
      { label: 'Persistance JPA', url: 'https://www.notion.so/2932ae802e29805fb27bc25ece0054b6' },
    ],
  },
  S7: {
    title: '🍃 Spring Boot 2',
    bloc: 'Spring Boot',
    notions: [
      'Logique métier : @Service, séparation des responsabilités',
      'Exceptions : @ExceptionHandler, @ControllerAdvice, HTTP status',
      'Variables d\'env : @Value, profiles Spring, .env',
    ],
    ia: 'L\'IA structure la couche service',
    ia_mode: 'copilot',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'Séparation métier/infra, configuration',
    links: [
      { label: '🍃 Spring Boot', url: 'https://satin-truffle-ac4.notion.site/Spring-Boot-28c2ae802e29802d9edecb8920734da3' },
      { label: 'Exposition REST', url: 'https://www.notion.so/28d2ae802e29800ba606db8dc36ea329' },
      { label: 'Exceptions', url: 'https://www.notion.so/2942ae802e2980259bffd960b7b654e8' },
      { label: 'Métier', url: 'https://www.notion.so/2952ae802e29800aa988e96aa1d44011' },
      { label: 'Variables d\'env', url: 'https://www.notion.so/2952ae802e29806aae92d17e48fa71f1' },
    ],
  },
  S8: {
    title: '🍃 Spring Boot 3',
    bloc: 'Spring Boot',
    notions: [
      'DI/IoC avancé : @Bean, injection constructeur',
      'Auth JWT : Spring Security, filtres, tokens',
      'Tests Spring : @SpringBootTest, MockMvc, @DataJpaTest',
    ],
    ia: '🤖 Ollama : appel LLM local depuis Spring Boot (feature e-shop IA)',
    ia_mode: 'delegation',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'Sécurité, tests d\'intégration',
    links: [
      { label: '🍃 Spring Boot', url: 'https://satin-truffle-ac4.notion.site/Spring-Boot-28c2ae802e29802d9edecb8920734da3' },
      { label: 'DI & IoC', url: 'https://www.notion.so/2952ae802e2980f19847d9fe4bf88bbd' },
      { label: 'Authentification JWT', url: 'https://www.notion.so/2952ae802e29801987a2c63850269da7' },
      { label: 'Tests', url: 'https://www.notion.so/2972ae802e2980f59da6d12372e5eeae' },
    ],
  },
  S9: {
    title: '🤖 CI/CD Spring Boot + Docker',
    bloc: 'CI/CD',
    notions: [
      'CI/CD Spring Boot : pipeline GitHub Actions complet',
      'Docker Compose : Spring Boot + PostgreSQL + Angular + Ollama',
      'Déploiement VPS : nginx reverse proxy, HTTPS, vars prod',
    ],
    ia: 'Prometheus + Grafana : monitoring containers + métriques Ollama',
    ia_mode: 'delegation',
    blocs_cda: ['BC03'],
    fondamentaux: 'Infrastructure, monitoring, déploiement',
    links: [
      { label: '🤖 CI-CD', url: 'https://satin-truffle-ac4.notion.site/CI-CD-2862ae802e298087b982f578be8782b7' },
      { label: 'CI + SpringBoot', url: 'https://satin-truffle-ac4.notion.site/CI-SpringBoot-2982ae802e29802bbb13dbf94d016724' },
      { label: 'CD + SpringBoot', url: 'https://satin-truffle-ac4.notion.site/CD-SpringBoot-2982ae802e2980e19a11cbace23a5082' },
      { label: '🐳 Docker', url: 'https://satin-truffle-ac4.notion.site/Docker-2852ae802e298038b5bbc1441663555c' },
      { label: 'Docker + Angular', url: 'https://satin-truffle-ac4.notion.site/Docker-Angular-2852ae802e29803dbf34dd8a41945285' },
      { label: 'Docker + SpringBoot', url: 'https://satin-truffle-ac4.notion.site/Docker-SpringBoot-2982ae802e2980e5bd1ff769c1bd0477' },
    ],
  },
  S10: {
    title: '🔧 Finalisation pipeline',
    bloc: 'CI/CD',
    notions: [
      'Pipeline fullstack bout-en-bout validé',
      'Monitoring Prometheus/Grafana opérationnel',
      'Revue architecture globale de l\'e-shop',
    ],
    ia: 'L\'IA analyse les logs d\'erreur du pipeline CI',
    ia_mode: 'delegation',
    blocs_cda: ['BC03'],
    fondamentaux: 'Qualité pipeline, observabilité',
    links: [
      { label: '🤖 CI-CD', url: 'https://satin-truffle-ac4.notion.site/CI-CD-2862ae802e298087b982f578be8782b7' },
      { label: '🐳 Docker', url: 'https://satin-truffle-ac4.notion.site/Docker-2852ae802e298038b5bbc1441663555c' },
    ],
  },
  S21: {
    title: '🚀 Projet — Démarrage',
    bloc: 'Projet',
    notions: [
      'Constitution groupes (temps plein)',
      'Alternants : structuration dossier entreprise',
      'Spec : architecture, backlog, git workflow, README',
    ],
    ia: 'L\'IA génère la doc d\'architecture et le README',
    ia_mode: 'delegation',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Gestion projet, architecture logicielle',
    links: [],
  },
  S22: {
    title: '📋 Préparation dossier',
    bloc: 'Certification',
    notions: [
      'Rédaction finale du dossier de projet',
      'Mapping compétences RNCP par BC',
      'Relecture croisée · corrections de fond',
    ],
    ia: 'L\'IA relit le dossier et identifie les zones faibles',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Rigueur documentaire, synthèse',
    links: [],
  },
  S23: {
    title: '🎤 Préparation aux épreuves',
    bloc: 'Certification',
    notions: [
      'Simulation jury en binôme · entraînement oral',
      'Révision BC01 · BC02 · BC03',
      'Posture professionnelle · gestion du stress',
    ],
    ia: 'L\'IA joue le rôle du jury : questions techniques et transversales',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Argumentation, posture professionnelle',
    links: [],
  },
  S24: {
    title: '🎓 Certification RNCP — TP',
    bloc: 'Certification',
    notions: [
      'Passage devant le jury RNCP37873',
      'Présentation dossier de projet',
      'Épreuve orale — semaine du 14 juin',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Validation des compétences CDA',
    links: [],
  },
  S34: {
    title: '🏫 Retour en centre — Alternants',
    bloc: 'Alternants',
    notions: [
      'Retour en centre (23–27 août) — alternants uniquement',
      'Contenu à définir',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: [],
    fondamentaux: 'À préciser',
    links: [],
  },
  S36: {
    title: '📋 Relecture des dossiers — Alternants',
    bloc: 'Certification',
    notions: [
      'Alternants uniquement (6–10 sept) — TP déjà terminés',
      'Relecture croisée des dossiers de projet',
      'Corrections finales · points de vigilance jury',
    ],
    ia: 'L\'IA identifie les zones faibles du dossier',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Synthèse, rigueur documentaire',
    links: [],
  },
  S37: {
    title: '🏢 Alternants en entreprise',
    bloc: 'Alternants',
    notions: [
      'Semaine entreprise (13–17 sept)',
      'À confirmer — peut varier selon les contrats',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: [],
    fondamentaux: '',
    links: [],
  },
  S38: {
    title: '🎤 Préparation aux épreuves',
    bloc: 'Certification',
    notions: [
      'Retour en centre (20–24 sept)',
      'Simulation jury en binôme · entraînement oral',
      'Révision BC01 · BC02 · BC03 · posture professionnelle',
    ],
    ia: 'L\'IA simule les questions du jury RNCP',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Argumentation technique, posture pro',
    links: [],
  },
  S39b: {
    title: '🎓 Certification RNCP — Alternants',
    bloc: 'Certification',
    notions: [
      'Passage devant le jury RNCP37873',
      'Présentation dossier entreprise ou portfolio',
      'Épreuve orale — 27 sept – 1er oct (à confirmer)',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Validation des compétences CDA',
    links: [],
  },
}
