import type { WeekContent } from '../types'

export const CONTENT: Record<string, WeekContent> = {
  S39: {
    title: '🚀 Accueil TP',
    bloc: 'Démarrage',
    notions: [
      'Install postes : Terminal, VS Code, Node, Git, extensions',
      'Comptes GitHub et Notion — mise en place du daily standup',
      'Diagnostic HTML/CSS/Terminal — qui vient d\'où, ce qui fait peur · adossé aux cours de l\'été (onglet Préparation) : la page perso de l\'été servira en S43',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: [],
    fondamentaux: 'Posture de développeur : je cherche avant de demander, je lis les erreurs',
    livrable: 'Checklist « environnement opérationnel » validée en binôme — Terminal, Node, Git, VS Code, comptes GitHub et Notion fonctionnels',
    links: [],
  },
  S40: {
    title: '🌼 JS — Fondamentaux',
    bloc: 'JavaScript',
    notions: [
      'Variables, types, if/else, boucles, fonctions — dans la console, pas de pseudocode',
      'Méthode résolution de problème (1h J1) : lire une erreur, couper en deux, chercher dans la doc',
      'Semaine sans IA : raisonnement pur — lire l\'erreur, formuler une hypothèse, tester · le réflexe d\'abord, la théorie IA arrive en S46',
    ],
    ia: 'Aucune — IA interdite cette semaine : ancrer le raisonnement sur les toutes premières lignes de code (théorie IA en S46)',
    ia_mode: 'solo',
    blocs_cda: ['BC01'],
    fondamentaux: 'JS = interprété, faiblement typé — coercition, NaN, undefined sont des failles par design, pas des bugs',
    livrable: 'Un fichier d\'exercices par notion (variables, boucles, fonctions), exécutables sans erreur dans la console',
    links: [
      { label: '🌼 JavaScript', url: 'https://satin-truffle-ac4.notion.site/Javascript-1d72ae802e29804596fbe823e86fa5a0' },
      { label: 'Qu\'est-ce que JS ?', url: 'https://www.notion.so/1d72ae802e298050b54df0ccebba21a5' },
      { label: 'Syntaxe & concepts', url: 'https://www.notion.so/1d72ae802e298049a83eed89d3a22e47' },
      { label: 'Variables', url: 'https://www.notion.so/1d72ae802e2980769052fff03bfee419' },
      { label: 'Types de données', url: 'https://www.notion.so/1d72ae802e29808f9a62dadf5479b520' },
    ],
  },
  S41: {
    title: '🌼 JS — Katas',
    bloc: 'JavaScript',
    notions: [
      'Katas repo JS : tests rouge→vert sur les notions de S40',
      'Pair tutoring : les plus avancés accompagnent les bloqués',
      'Débrief collectif J1 matin : remonter les blocages de S40',
    ],
    ia: 'Comparer sa solution avec la proposition IA — expliquer les différences',
    ia_mode: 'mixed',
    blocs_cda: ['BC01'],
    fondamentaux: 'Récupération active : se souvenir coûte et consolide — relire le cours ne vaut rien',
    livrable: 'Katas du repo JS au vert (rouge→vert) + une solution expliquée à l\'oral au débrief',
    links: [
      { label: '🌼 JavaScript', url: 'https://satin-truffle-ac4.notion.site/Javascript-1d72ae802e29804596fbe823e86fa5a0' },
      { label: 'Opérateurs conditionnels', url: 'https://www.notion.so/1d72ae802e2980389e60e63e3e7df3a4' },
      { label: 'Fonctions', url: 'https://www.notion.so/1d72ae802e29803584c6cb3a1a8b0466' },
      { label: 'Tableaux', url: 'https://www.notion.so/1d72ae802e2980408b7dc81d345c8d06' },
      { label: 'Méthodes des tableaux', url: 'https://www.notion.so/1d72ae802e2980808155dbef61cd293e' },
    ],
  },
  S42: {
    title: '🌼 JS avancé + 🐙 Git',
    bloc: 'JavaScript',
    extraBlocs: ['Git'],
    notions: [
      'J1-J3 : JS avancé — arrays, objets, destructuring, spread, méthodes fonctionnelles (map/filter/reduce)',
      'Pureté vécue avant d\'être nommée : kata où un .map() mute silencieusement → on pose ensuite les mots « fonction pure » et « effet de bord »',
      'J4-J5 : Git — clone, commit, branch, merge · leur code JS de J1-J3 comme premier dépôt versionné',
    ],
    ia: 'Générer des messages de commit → évaluer leur qualité et leur utilité',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC03'],
    fondamentaux: 'Fonctions pures = pas d\'effet de bord = prédictibles · Git = graphe orienté acyclique — force-push sur main = catastrophe',
    livrable: 'Le code JS de S40-S41 versionné : repo Git avec historique de commits propres',
    links: [
      { label: '🐙 Git & GitHub', url: 'https://www.notion.so/Git-Github-3732ae802e298081a206e7f550efe9d6' },
      { label: '1️⃣ Git local', url: 'https://www.notion.so/3732ae802e298194b9c3dc49d0ceb550' },
    ],
  },
  S43: {
    title: '🐙 Git — Mini-projet GitHub Pages',
    bloc: 'Git',
    notions: [
      'Katas JS sur arrays/objets — consolidation S42',
      'Mini-projet : site HTML/CSS personnel versionné sur GitHub, déployé sur GitHub Pages (CI auto)',
      'PR et review croisée entre binômes — conventional commits',
    ],
    ia: 'L\'IA génère un README — évaluer la précision et la pertinence',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC03'],
    fondamentaux: 'Un historique Git propre se lit comme un journal — conventional commits + PR reviews = pratique pro dès le départ',
    livrable: 'Site perso HTML/CSS déployé sur GitHub Pages, avec PR reviewée par un binôme',
    links: [
      { label: '🐙 Git & GitHub', url: 'https://www.notion.so/Git-Github-3732ae802e298081a206e7f550efe9d6' },
      { label: '1️⃣ Git local', url: 'https://www.notion.so/3732ae802e298194b9c3dc49d0ceb550' },
    ],
  },
  S44: {
    title: '🎯 Conception V1 — Use case · Architecture · Métier',
    bloc: 'Vision métier',
    extraBlocs: ['Conception'],
    notions: [
      'J1 matin : la chaîne complète — besoin client → analyse → cahier des charges → spécification : interview client fictif, CDC e-shop, user stories · chaque étape produit un artefact nommé',
      'J1 après-midi : l\'agilité comme réponse — rôles (PO, dev), backlog et priorisation MoSCoW, sprint, daily, rétro · Scrum vs Kanban vs mix (Scrumban) · board créé séance tenante (Trello ou GitHub Projects) avec les user stories du matin, priorisées ensemble',
      'J2 : pour chaque user story de J1 — précondition (l\'utilisateur est-il connecté ?), invariant métier (un panier vide ne se commande pas, une quantité est toujours ≥ 1), embranchements (flux nominal / alternatif / erreur)',
      'J3 : Architecture N-tiers — schéma e-shop dessiné ensemble · chaque couche a ses invariants : le frontend ne touche jamais la BDD, l\'API ne retourne jamais de mot de passe',
      'J4-J5 : UML use case — acteurs, cas d\'utilisation, relations include/extend · pour chaque cas d\'utilisation : préconditions et postconditions écrites avant de dessiner',
    ],
    ia: 'J1-J3 : sans IA — réflexion pure sur les invariants et la logique métier · J4-J5 : l\'IA génère un diagramme use case → évaluer si les embranchements métier sont bien représentés',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Un invariant métier = une règle qui ne doit jamais être violée, quelle que soit la couche · Modéliser les préconditions et embranchements dès la conception évite de les découvrir comme bugs en production · La chaîne besoin → CDC → spec → backlog est le squelette de tout projet pro — l\'agilité ne remplace pas l\'analyse, elle l\'itère',
    livrable: 'CDC e-shop + user stories (préconditions, invariants) + diagramme use case — déposés dans le repo de groupe + board Kanban initialisé',
    links: [],
  },
  S45: {
    title: '🎨 Conception V1 — Figma · Maquettes · XSS',
    bloc: 'Vision métier',
    extraBlocs: ['Fil rouge', 'Conception'],
    notions: [
      'J1-J3 : Figma — wireframes puis maquettes des écrans clés e-shop · Pour chaque écran : modéliser tous les états (vide, chargement, erreur, succès) — chaque état correspond à une précondition différente · les embranchements visuels doivent refléter les embranchements métier de S44 · priorisation MoSCoW des écrans : le MVP d\'abord, le gold plating identifié et remis au backlog',
      'J4-J5 : XSS découverte sur page vulnérable FOURNIE — attaquer, puis corriger (primo-exposition guidée, consolidation en S46) · lien avec les invariants : "toute donnée utilisateur est hostile" = invariant de sécurité absolu',
    ],
    ia: 'J1-J3 : IA pour accélérer la production Figma · vérifier que les maquettes couvrent les embranchements de S44 · J4-J5 : XSS d\'abord sans IA (comprendre l\'attaque par soi-même), puis l\'IA explique les vecteurs et leurs variantes',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'Un wireframe sans ses états d\'erreur est incomplet — les embranchements métier doivent être visibles dans les maquettes avant d\'être codés · XSS : invariant de sécurité — toute donnée utilisateur est hostile',
    livrable: 'Maquettes Figma des écrans clés (tous états : vide, chargement, erreur, succès) + page XSS corrigée + backlog priorisé (MoSCoW)',
    links: [],
  },
  S46: {
    title: '🤖 IA fondamentaux + Sécurité',
    bloc: 'IA',
    notions: [
      'J1 : manipulation d\'abord — faire halluciner un LLM, observer tokens et fenêtre de contexte en direct · on nomme ensuite : prédiction du token suivant, embeddings',
      'J2 : hallucinations, biais, injection de prompt — pourquoi ce sont des failles structurelles · éthique et RGPD en fin de journée (1h, cas concrets), pas en bloc théorique',
      'J3 : XSS consolidation + OWASP Top 10 intro (rattrapage ALT qui ont raté S45)',
      'J4 : Prompt maïeutique vs délégation — pratique sur du code JS qu\'ils connaissent',
    ],
    ia: 'Séance fondatrice : anatomie d\'un LLM — comprendre pourquoi il confabule avant de lui faire confiance',
    ia_mode: 'theory',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'LLM = prédiction du token suivant — confabulation, biais, drift de contexte, injection de prompt sont des failles structurelles',
    livrable: 'Fiche réflexe IA personnelle : quand l\'utiliser, quand s\'en méfier — 3 hallucinations provoquées et documentées',
    links: [],
  },
  S47: {
    title: '🌼 JS async — fetch & Promises',
    bloc: 'JavaScript',
    notions: [
      'fetch, async/await, gestion d\'erreurs (.catch, try/catch), Promise.all',
      'Event loop mono-thread : J1-J2 tracer l\'ordre d\'exécution des Promises à la main, sans IA · ce qui bloque l\'event loop (boucle synchrone infinie, JSON.parse massif)',
      'Katas : mini-app qui consomme une API publique — squelette fourni (primo-exposition guidée, consolidée en S48 par la migration TS du module async) · lecture doc MDN en anglais imposée',
    ],
    ia: 'J1-J2 : sans IA — tracer l\'ordre d\'exécution à la main · J3-J5 : déboguer du code async avec l\'IA — race conditions et unhandled rejections',
    ia_mode: 'mixed',
    blocs_cda: ['BC01'],
    fondamentaux: 'JS est mono-thread — l\'event loop ne bloque pas, mais certaines ops bloquent l\'event loop : les reconnaître évite les freezes prod',
    livrable: 'Mini-app fetch fonctionnelle sur API publique (squelette complété) + schéma de l\'event loop tracé à la main',
    links: [
      { label: '🌼 JavaScript', url: 'https://satin-truffle-ac4.notion.site/Javascript-1d72ae802e29804596fbe823e86fa5a0' },
      { label: 'Boucles', url: 'https://www.notion.so/1d72ae802e2980b881d6c414ea119ec1' },
      { label: 'Objets', url: 'https://www.notion.so/1d72ae802e2980e8b3fff6f834f6b7cd' },
      { label: 'DOM', url: 'https://www.notion.so/1d72ae802e298060acc2f8e22d0915de' },
    ],
  },
  S48: {
    title: '🟦 TypeScript + JS Bundle',
    bloc: 'TypeScript',
    notions: [
      'Types de base, interfaces, type guards · migration du module async/fetch de S47 → TS strict : typer les Promises et les réponses d\'API (consolidation async à J+7)',
      'TS disparaît au runtime — ce qu\'il ne protège pas (erreurs réseau, JSON externe, any qui contamine)',
      'JS bundle intro : qu\'est-ce qu\'un bundler, build pipeline, tree shaking, source maps, prod vs dev',
    ],
    ia: 'J1-J2 : sans IA — ancrer le système de types · J3-J5 : l\'IA génère du TS typé → repérer les dérives (any implicite)',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'TS disparaît au runtime — fausse sécurité si on ne comprend pas cette limite · Bundle = votre code ≠ ce qui arrive au browser',
    livrable: 'Module async de S47 migré en TS strict — zéro any, compilation sans erreur',
    links: [{ label: '🟦 TypeScript', url: 'https://satin-truffle-ac4.notion.site/Typescript-25d2ae802e2980a79ea5e8a48349fb33' }],
  },
  S49: {
    title: '🟦 TS katas + Modélisation fil rouge',
    bloc: 'TypeScript',
    extraBlocs: ['Fil rouge'],
    notions: [
      'Katas TypeScript — types avancés, utility types (Partial, Pick, Omit)',
      'Rappel Conception (S44, J+21) : relire les use cases e-shop — chaque interface TS doit correspondre à un cas d\'utilisation et ses invariants',
      'Angular CLI : install + observation du premier composant généré (lecture guidée, pas de cours)',
    ],
    ia: 'L\'IA génère les interfaces TS pour le modèle e-shop → vérifier la cohérence avec le schéma BDD',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'Modéliser avant de coder — les types TS sont la traduction du modèle métier : une interface qui ne correspond à aucun invariant est du bruit',
    livrable: 'Katas utility types au vert + interfaces TS du modèle e-shop alignées sur les use cases de S44',
    links: [{ label: '🟦 TypeScript', url: 'https://satin-truffle-ac4.notion.site/Typescript-25d2ae802e2980a79ea5e8a48349fb33' }],
  },
  S50: {
    title: '🛡️ Angular — Fondamentaux framework',
    bloc: 'Angular',
    notions: [
      'J1 : pipeline Angular (TS→JS→bundle→browser) · SSOT & flux unidirectionnel — pourquoi avant comment',
      'J2-J4 : @Component, binding, @Input/@Output — comprendre le mécanisme avant de l\'utiliser, pratiquer sur des composants simples',
      'J5 : Signals présentés, pas pratiqués — modèle mental « source de vérité réactive » posé dès maintenant, la pratique arrive en S51 sur le fil rouge',
    ],
    ia: 'J1-J2 : sans IA — comprendre le pipeline et le binding · J3-J5 : l\'IA génère un composant → analyser la structure',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'SSOT = source unique de vérité — état dupliqué = bugs silencieux · Signals = réactivité fine sans zone.js · Flux unidirectionnel = prédictibilité et debugging',
    livrable: 'Composant Angular avec @Input/@Output fonctionnel + schéma annoté du pipeline TS→browser',
    links: [
      { label: '🛡️ Angular', url: 'https://satin-truffle-ac4.notion.site/Angular-2092ae802e298032b6e6f8db22315706' },
      { label: 'Les Composants', url: 'https://www.notion.so/2092ae802e298034b8bcff5ca18a33ef' },
      { label: 'Les Templates', url: 'https://www.notion.so/2092ae802e298030857de758641e5ffc' },
    ],
  },
  S51: {
    title: '🛡️ Angular — Démarrage fil rouge e-shop',
    bloc: 'Angular',
    extraBlocs: ['Fil rouge'],
    notions: [
      'Setup repo fil rouge e-shop : architecture décidée, conventions posées, CI configurée',
      'Premier composant réel sur leur propre projet — pas un kata, pas un tuto',
      'Pas de nouveau concept Angular : consolider @Component + Signals sur du vrai code',
      'Le fil rouge tourne en Scrumban dès maintenant : le board de S44-S45 migre dans le repo d\'équipe (Trello/GitHub Projects), PO tournant par sprint, sprint = 1 semaine, daily 10 min — la rétro vit dans le débrief du lendemain',
    ],
    ia: 'L\'IA aide à scaffolder la structure du projet — l\'apprenant valide chaque décision d\'architecture',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Un projet réel n\'est pas un kata — les décisions d\'architecture ont des conséquences : les poser maintenant, pas à mi-parcours',
    livrable: 'Repo e-shop de groupe initialisé : architecture, conventions, CI template, premier composant mergé + board Scrumban actif (backlog repris de S44-S45)',
    links: [
      { label: '🛡️ Angular', url: 'https://satin-truffle-ac4.notion.site/Angular-2092ae802e298032b6e6f8db22315706' },
      { label: 'Signals', url: 'https://www.notion.so/2622ae802e2980d496d3c155dee2b445' },
    ],
  },
  S1: {
    title: '🛡️ Angular — Router · Services · HttpClient',
    bloc: 'Angular',
    notions: [
      'J1 : Router — routes, RouterLink, ActivatedRoute, guards',
      'J2 : formulaires réactifs — FormGroup, FormControl, Validators',
      'J3 : services @Injectable — injection de dépendances : le framework gère les instances',
      'J4-J5 : HttpClient (GET/POST/PUT/DELETE) — appels typés vers une API, gestion des erreurs',
    ],
    ia: 'J1-J3 : sans IA (routing, formulaires, services) · J4-J5 : l\'IA génère les calls HttpClient → analyser les types de retour',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'DI = singleton géré par le framework · Routing client-side ≠ routing serveur (History API, 404 nginx) · HttpClient = abstraction typée sur fetch',
    livrable: 'Mini-app routée avec guard + formulaire réactif validé + service HttpClient typé',
    links: [
      { label: '🛡️ Angular', url: 'https://satin-truffle-ac4.notion.site/Angular-2092ae802e298032b6e6f8db22315706' },
      { label: 'Le Router', url: 'https://www.notion.so/26f2ae802e298009ac6bdda6ae01dc94' },
      { label: 'Les Formulaires', url: 'https://www.notion.so/2702ae802e298018a7e9db10423fa1d3' },
      { label: 'Les Services', url: 'https://www.notion.so/2092ae802e2980b48156f021815221dd' },
      { label: 'Les requêtes HTTP', url: 'https://www.notion.so/2092ae802e2980438132eeb436479620' },
    ],
  },
  S2: {
    title: '🛡️ Angular — Katas fil rouge (Router + Services)',
    bloc: 'Angular',
    extraBlocs: ['Fil rouge'],
    notions: [
      'Application des notions sur le projet e-shop : routes, guards, formulaire de connexion/inscription',
      'Services Angular : pattern Repository, state management simple avec Signals',
      'Appels HTTP e-shop : liste produits, panier — calls réels (mock) vers l\'API Spring Boot à venir',
      'Sprint review fil rouge : démo des features, re-priorisation MoSCoW du backlog — qu\'est-ce qui a de la valeur pour le sprint suivant ?',
    ],
    ia: 'L\'IA génère un service complet → analyser la structure, le pattern, les edge cases',
    ia_mode: 'copilot',
    blocs_cda: ['BC01'],
    fondamentaux: 'Un service @Injectable est un singleton — toute mutation d\'état dans un service affecte tous les composants qui l\'injectent',
    livrable: 'Sur l\'e-shop : routes, guard, formulaire de connexion et service produits (mock) mergés via PR',
    links: [
      { label: '🛡️ Angular', url: 'https://satin-truffle-ac4.notion.site/Angular-2092ae802e298032b6e6f8db22315706' },
      { label: 'Les Services', url: 'https://www.notion.so/2092ae802e2980b48156f021815221dd' },
      { label: 'Signals', url: 'https://www.notion.so/2622ae802e2980d496d3c155dee2b445' },
    ],
  },
  S3: {
    title: '☕ Java — Syntaxe + POO + Exceptions',
    bloc: 'Java',
    notions: [
      'J1 : la rupture nommée — JS/TS interprété vs Java compilé fortement typé : ce que les types TS ont déjà appris, ce qui change vraiment · JDK, Hello World en 10 min',
      'J2 : syntaxe Java en katas — types primitifs, méthodes, boucles, tableaux',
      'J3 : classes et encapsulation · J4 : héritage vs composition (fragile base class problem), interfaces',
      'J5 : exceptions — early return > catch silencieux · JUnit 5 intro (@Test, assertions, @BeforeEach) : premier test réel sur leur code · démo 30 min Streams (filter/map/collect) sur la collection qu\'ils viennent de tester — ancre pour S4',
    ],
    ia: 'L\'IA explique les stack traces Java · L\'IA génère des tests JUnit → vérifier la pertinence des assertions',
    ia_mode: 'mixed',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'Java = compilé, fortement typé — erreur de type à la compilation, pas au runtime · Héritage vs composition — fragile base class problem · Exceptions : early return + exception typée > catch silencieux',
    livrable: 'Classes Java POO (héritage vs composition) + premier test JUnit vert sur leur propre code',
    links: [
      { label: '☕ Java', url: 'https://satin-truffle-ac4.notion.site/Java-1f82ae802e2980f49405d0b5c5c311c6' },
      { label: 'JDK', url: 'https://www.notion.so/1f82ae802e29806188f1fbc5a483891f' },
      { label: 'Syntaxe & algo', url: 'https://www.notion.so/1f82ae802e298032b68dfa449bcd50be' },
      { label: 'Variables', url: 'https://www.notion.so/1f82ae802e298006a308dcf3d64ebc73' },
      { label: 'POO bases', url: 'https://www.notion.so/1fa2ae802e29800ba078c4c848702b55' },
      { label: 'Héritage', url: 'https://www.notion.so/1f82ae802e2980fb8edbe864030c1284' },
      { label: 'Interfaces', url: 'https://www.notion.so/1f82ae802e2980c7ada0ed11d62b5f7c' },
    ],
  },
  S4: {
    title: '☕ Java — Katas + Streams + JUnit',
    bloc: 'Java',
    extraBlocs: ['Conception'],
    notions: [
      'Katas Java approfondis : collections, méthodes complexes, conditions imbriquées',
      'Streams API en primo-exposition guidée (démo vue en S3) : filter, map, collect, Optional — katas sur exemples fournis : comprendre et adapter avant d\'écrire de zéro',
      'Conception Passe 2 — Diagramme de classes V1 : entités e-shop (Produit, Commande, Utilisateur), relations, cardinalités · invariants de classe (un Produit sans prix est invalide dès la construction) · préconditions des méthodes métier · les classes Java qu\'ils viennent d\'écrire deviennent le modèle',
    ],
    ia: 'L\'IA génère des tests JUnit → vérifier la couverture et repérer les assertions superficielles',
    ia_mode: 'mixed',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'Tester via l\'API publique, jamais les méthodes privées · Diagramme de classes = contrat structurel — les invariants y sont lisibles avant même d\'ouvrir le code · un constructeur qui laisse passer un objet invalide est une faille de conception',
    livrable: 'Katas Streams adaptés au vert + diagramme de classes V1 e-shop avec invariants annotés',
    links: [
      { label: '☕ Java', url: 'https://satin-truffle-ac4.notion.site/Java-1f82ae802e2980f49405d0b5c5c311c6' },
      { label: 'Tableaux & itérations', url: 'https://www.notion.so/1f82ae802e2980769004f379d4443c34' },
      { label: 'ArrayList', url: 'https://www.notion.so/1f82ae802e29805ebf2ad1599ee68aee' },
    ],
  },
  S5: {
    title: '🗄️ SQL — Modélisation + Requêtes + NoSQL concept',
    bloc: 'SQL',
    extraBlocs: ['Conception'],
    notions: [
      'J1-J2 : Conception Passe 2 suite — du diagramme de classes (S4) au MLD : traduction des relations en tables, cardinalités → clés étrangères · contraintes SQL = invariants BDD (NOT NULL, UNIQUE, FK — un enregistrement sans contrainte est une promesse sans garantie)',
      '🕵️ J3 : SQL Murder Mystery — katas en contexte narratif (agrégats, COUNT, GROUP BY, HAVING, sous-requêtes)',
      'J4 : injections SQL — attaquer une requête vulnérable puis la paramétrer · NoSQL concept (1h) — document store vs relationnel, cas d\'usage MongoDB, pas d\'implémentation',
      'J5 : index et EXPLAIN — lire un plan d\'exécution, poser un index, mesurer la différence',
    ],
    ia: 'L\'IA explique un plan d\'exécution SQL (EXPLAIN) et génère des requêtes → repérer les injections potentielles',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'Un schéma BDD est une décision d\'architecture — modifier une colonne en prod coûte cher · Injection SQL = faille #1 OWASP · NoSQL = choix selon le cas d\'usage, pas un remplacement',
    livrable: 'MLD e-shop traduit du diagramme de classes + script SQL avec contraintes (NOT NULL, UNIQUE, FK) exécutable',
    links: [],
  },
  S6: {
    title: '🗄️ SQL katas + 🍃 Spring Boot preview',
    bloc: 'SQL',
    extraBlocs: ['Spring Boot'],
    notions: [
      'SQL katas consolidation : requêtes complexes, sous-requêtes, optimisation — sur le schéma e-shop réel',
      'Java Streams + JUnit approfondissement : filter, map, collect, Optional',
      'Spring Boot preview : lecture doc officielle en anglais (Servlet, IoC) — fondamentaux avant le code',
    ],
    ia: 'L\'IA explique les différences entre INNER JOIN, LEFT JOIN et FULL OUTER JOIN avec des exemples',
    ia_mode: 'mixed',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'SQL Murder Mystery : apprendre en contexte narratif — la motivation est la meilleure charge cognitive',
    livrable: 'Requêtes complexes au vert sur le schéma e-shop + fiche de lecture Spring (Servlet, IoC) en anglais',
    links: [],
  },
  S7: {
    title: '🍃 Spring Boot 1 — JPA + REST + Sécurité',
    bloc: 'Spring Boot',
    notions: [
      'J1 : IoC vécu avant d\'être nommé — câbler les dépendances à la main (new partout), sentir la douleur, puis laisser le conteneur Spring la faire disparaître · beans, proxy',
      'J2-J3 : JPA — @Entity, @Repository, Spring Data · CRUD endpoints REST · N+1 queries (faille classique silencieuse)',
      'J4 : diagramme de séquence dessiné ensemble : controller → service → repository → BDD — rend visibles l\'IoC et le N+1, ancre la notation pour S8 · schéma BDD e-shop formalisé (script SQL)',
      'J5 : sécurité allégée — CORS + variables d\'env jamais en dur (HTTPS reporté à S10 avec Let\'s Encrypt) · lecture d\'un JWT sur jwt.io (30 min — ancre pour S9)',
    ],
    ia: 'L\'IA génère une entité JPA + repository → vérifier les annotations et détecter les N+1 potentiels',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Spring = conteneur IoC — les beans sont gérés par le framework · N+1 query = SELECT dans une boucle = catastrophe en production',
    livrable: 'API CRUD JPA fonctionnelle + diagramme de séquence du pipeline + script SQL e-shop versionné',
    links: [
      { label: '🍃 Spring Boot', url: 'https://satin-truffle-ac4.notion.site/Spring-Boot-28c2ae802e29802d9edecb8920734da3' },
      { label: 'Introduction au backend', url: 'https://www.notion.so/28d2ae802e29802b9dd8f377f61029ec' },
      { label: 'Introduction Spring Boot', url: 'https://www.notion.so/28d2ae802e298010832dee900e0bf0ab' },
      { label: 'Persistance JPA', url: 'https://www.notion.so/2932ae802e29805fb27bc25ece0054b6' },
    ],
  },
  S8: {
    title: '🍃 Spring Boot — Katas + Plan de tests',
    bloc: 'Spring Boot',
    extraBlocs: ['Fil rouge', 'Conception'],
    notions: [
      'Katas Spring Boot sur squelette de couche service FOURNI : @Service, séparation des responsabilités, @ExceptionHandler · Design patterns nommés : Repository (accès données), Strategy (comportement interchangeable) — les reconnaître dans le code Spring pour savoir les argumenter au jury',
      'Plan de tests formalisé : template, jeu d\'essai, données attendues vs obtenues — à remplir pour l\'e-shop',
      'Conception Passe 3 — Diagramme de séquence : modéliser 2 flux critiques e-shop (auth JWT, ajout panier) · fragments combinés UML : alt (embranchements), opt (optionnel), loop — les préconditions et invariants de la Passe 1 deviennent des fragments de séquence formels',
    ],
    ia: 'J1-J2 : sans IA — structurer la couche service soi-même sur le squelette fourni · J3-J5 : faire critiquer sa séparation des responsabilités par l\'IA',
    ia_mode: 'mixed',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'Plan de tests = contrat de confiance · Diagramme de séquence : chaque fragment alt est un embranchement métier — si tu ne peux pas le dessiner, tu ne l\'as pas compris · Design patterns = vocabulaire partagé pour argumenter une décision d\'architecture · @ExceptionHandler global : 4xx expose le message (safe), 5xx message générique (sécurité)',
    livrable: 'Couche service structurée sur le squelette fourni + plan de tests e-shop rempli (template)',
    links: [
      { label: '🍃 Spring Boot', url: 'https://satin-truffle-ac4.notion.site/Spring-Boot-28c2ae802e29802d9edecb8920734da3' },
      { label: 'Exposition REST', url: 'https://www.notion.so/28d2ae802e29800ba606db8dc36ea329' },
      { label: 'Exceptions', url: 'https://www.notion.so/2942ae802e2980259bffd960b7b654e8' },
      { label: 'Métier', url: 'https://www.notion.so/2952ae802e29800aa988e96aa1d44011' },
      { label: 'Tests', url: 'https://www.notion.so/2972ae802e2980f59da6d12372e5eeae' },
    ],
  },
  S9: {
    title: '🍃 Spring Security + JWT + 🐳 Docker',
    bloc: 'Spring Boot',
    extraBlocs: ['CI/CD', 'Fil rouge'],
    notions: [
      'J1-J2 : Spring Security & JWT — filtre FOURNI : lire, exécuter, modifier (claims signés, pas chiffrés — ce qu\'on peut lire, ce qu\'on ne doit jamais y mettre)',
      'J3 : bcrypt, hachage des mots de passe, rotation des tokens, expiration — katas sur le filtre de J1',
      'J4 : Docker — Dockerfile et docker-compose FOURNIS (Spring Boot + PostgreSQL) : lancer, lire, adapter — réutilisés en prod en S10 · J5 : Ollama en démo guidée — appel LLM local depuis Spring Boot (feature e-shop IA)',
    ],
    ia: 'J1-J2 : sans IA — lire le filtre JWT fourni ligne par ligne · J3-J5 : l\'IA explique chaque ligne du filtre et du compose — comprendre, pas générer',
    ia_mode: 'mixed',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'JWT = claims signés, pas chiffrés — lire le payload avec jwt.io · bcrypt = irréversible par design · Docker = reproductibilité, pas de "ça marche sur mon poste"',
    livrable: 'Filtre JWT modifié et expliqué ligne à ligne + stack docker-compose lancée en local',
    links: [
      { label: '🍃 Spring Boot', url: 'https://satin-truffle-ac4.notion.site/Spring-Boot-28c2ae802e29802d9edecb8920734da3' },
      { label: 'Authentification JWT', url: 'https://www.notion.so/2952ae802e29801987a2c63850269da7' },
      { label: '🐳 Docker', url: 'https://satin-truffle-ac4.notion.site/Docker-2852ae802e298038b5bbc1441663555c' },
      { label: 'Docker + SpringBoot', url: 'https://satin-truffle-ac4.notion.site/Docker-SpringBoot-2982ae802e2980e5bd1ff769c1bd0477' },
    ],
  },
  S10: {
    title: '⚙️ CI/CD Fullstack + Anglais certif',
    bloc: 'CI/CD',
    extraBlocs: ['Fil rouge', 'Conception'],
    notions: [
      'GitHub Actions fullstack : lint, tests, build Angular + Spring Boot, déploiement VPS',
      'nginx reverse proxy, HTTPS Let\'s Encrypt, variables secrets GitHub, docker-compose prod · Livrable fil rouge obligatoire : diagramme de déploiement (VPS, nginx, containers, BDD) — artefact attendu dans le dossier de projet CDA',
      'Prépa questionnaire anglais B1 (format certif : QCM + 2 questions ouvertes répondues en anglais)',
    ],
    ia: 'J1-J2 : sans IA — pipeline minimal et config nginx écrits à la main · J3-J5 : l\'IA génère le workflow complet, relecture step by step · L\'IA simule le questionnaire anglais RNCP',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Un pipeline = automatisation de la confiance — drift, secrets en clair, déploiement manuel = les 3 failles classiques de la mise en prod',
    livrable: 'Pipeline GitHub Actions vert sur l\'e-shop + diagramme de déploiement (artefact du dossier CDA)',
    links: [
      { label: '🤖 CI-CD', url: 'https://satin-truffle-ac4.notion.site/CI-CD-2862ae802e298087b982f578be8782b7' },
      { label: 'CI + Angular', url: 'https://satin-truffle-ac4.notion.site/CI-Angular-2862ae802e2980389270d94059214d69' },
      { label: 'CD + Angular', url: 'https://satin-truffle-ac4.notion.site/CD-Angular-2862ae802e29806aad19d2e25670febe' },
      { label: 'CI + SpringBoot', url: 'https://satin-truffle-ac4.notion.site/CI-SpringBoot-2982ae802e29802bbb13dbf94d016724' },
      { label: 'CD + SpringBoot', url: 'https://satin-truffle-ac4.notion.site/CD-SpringBoot-2982ae802e2980e19a11cbace23a5082' },
      { label: '🐳 Docker', url: 'https://satin-truffle-ac4.notion.site/Docker-2852ae802e298038b5bbc1441663555c' },
    ],
  },
  S21: {
    title: '🔄 Reprise post-stage',
    bloc: 'Certification',
    notions: [
      'Diagnostic technique post-stage : ce qui a été pratiqué, ce qui a été oublié, ce qui surprend',
      'Remobilisation : daily standup repris, veille reprise, repo fil rouge relu',
      'Points blocages stage — ce qu\'ils auraient eu besoin de savoir',
      'Katas de reprise : CI/CD + Docker (S10) et async (S47) — les notions vues une seule fois avant le stage, réancrées',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Le stage révèle les vraies lacunes — ce diagnostic oriente les 3 semaines de préparation',
    livrable: 'Fiche auto-bilan de stage (pratiqué / oublié / surpris) — input direct de S22',
    links: [],
  },
  S22: {
    title: '📋 Dossier + Simulation jury',
    bloc: 'Certification',
    notions: [
      'Finalisation dossier de projet (rédigé pendant le stage) — mapping compétences RNCP par CCP · la démarche agile du fil rouge (board, sprints, rétros) documentée comme preuve de gestion de projet (BC01)',
      'Relecture croisée · corrections de fond · structure 40-60 pages vérifiée',
      'Simulation jury partielle · entraînement anglais certif session 1 (QCM + ouvertes)',
    ],
    ia: 'L\'IA relit le dossier et identifie les zones faibles · L\'IA joue le rôle du jury en anglais',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Rigueur documentaire : un dossier bien structuré raconte une histoire de montée en compétences — pas une liste de tâches',
    livrable: 'Dossier de projet relu en croisé : mapping RNCP par CCP complété, structure 40-60 pages validée',
    links: [],
  },
  S23: {
    title: '🎤 Simulation jury + Anglais certif',
    bloc: 'Certification',
    notions: [
      'Simulation jury complète en binôme : 40min présentation + 45min entretien technique simulé',
      'Révision BC01/BC02/BC03 — points faibles identifiés en S22 traités en priorité',
      'Questionnaire anglais session 2 : 2 QCM + 2 questions ouvertes répondues en anglais (format certif exact)',
    ],
    ia: 'L\'IA joue le rôle du jury : questions techniques et transversales · simule le questionnaire anglais RNCP',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Posture professionnelle : argumenter une décision d\'architecture vaut mieux que réciter une définition',
    livrable: 'Grille de feedback jury remplie par le binôme + liste des points faibles à retravailler',
    links: [],
  },
  S24: {
    title: '🎓 Certification RNCP — TP',
    bloc: 'Certification',
    notions: [
      'Passage devant le jury RNCP37873',
      'Présentation dossier de projet',
      'Épreuve orale — semaine du 14 juin',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Validation des compétences CDA',
    links: [],
  },
  S34: {
    title: '🏫 Retour en centre — Alternants',
    bloc: 'Alternants',
    notions: [
      'Retour en centre (23–27 août) — alternants uniquement',
      'Contenu à définir',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: [],
    fondamentaux: 'À préciser',
    links: [],
  },
  S36: {
    title: '📋 Relecture des dossiers — Alternants',
    bloc: 'Certification',
    notions: [
      'Alternants uniquement (6–10 sept) — TP déjà terminés',
      'Relecture croisée des dossiers de projet',
      'Corrections finales · points de vigilance jury',
    ],
    ia: 'L\'IA identifie les zones faibles du dossier',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Synthèse, rigueur documentaire',
    livrable: 'Dossier annoté : zones faibles identifiées + corrections planifiées',
    links: [],
  },
  S37: {
    title: '🏢 Alternants en entreprise',
    bloc: 'Alternants',
    notions: [
      'Semaine entreprise (13–17 sept)',
      'À confirmer — peut varier selon les contrats',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: [],
    fondamentaux: '',
    links: [],
  },
  S38: {
    title: '🎤 Préparation aux épreuves',
    bloc: 'Certification',
    notions: [
      'Retour en centre (20–24 sept)',
      'Simulation jury en binôme · entraînement oral',
      'Révision BC01 · BC02 · BC03 · posture professionnelle',
    ],
    ia: 'L\'IA simule les questions du jury RNCP',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Argumentation technique, posture pro',
    livrable: 'Grille RNCP d\'auto-évaluation remplie + un passage oral complet chronométré avec feedback',
    links: [],
  },
  S39b: {
    title: '🎓 Certification RNCP — Alternants',
    bloc: 'Certification',
    notions: [
      'Passage devant le jury RNCP37873',
      'Présentation dossier entreprise ou portfolio',
      'Épreuve orale — 27 sept – 1er oct (à confirmer)',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Validation des compétences CDA',
    links: [],
  },
}
