import type { WeekContent } from '../types'

export const CONTENT: Record<string, WeekContent> = {
  S39: {
    title: '🚀 Accueil TP',
    bloc: 'Démarrage',
    notions: [
      'Install postes : Terminal, VS Code, Node, Git, extensions',
      'Comptes GitHub et Notion — mise en place du daily standup',
      'Diagnostic HTML/CSS/Terminal — qui vient d\'où, ce qui fait peur',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: [],
    fondamentaux: 'Posture de développeur : je cherche avant de demander, je lis les erreurs',
    links: [],
  },
  S40: {
    title: '🌼 JS — Fondamentaux',
    bloc: 'JavaScript',
    notions: [
      'Variables, types, if/else, boucles, fonctions — dans la console, pas de pseudocode',
      'Méthode résolution de problème (1h J1) : lire une erreur, couper en deux, chercher dans la doc',
      'IA en observation : on voit ce qu\'elle propose, on n\'accepte rien sans comprendre',
    ],
    ia: 'J1-J5 : observer les suggestions Copilot — ne rien accepter sans comprendre pourquoi',
    ia_mode: 'theory',
    blocs_cda: ['BC01'],
    fondamentaux: 'JS = interprété, faiblement typé — coercition, NaN, undefined sont des failles par design, pas des bugs',
    links: [
      { label: '🌼 JavaScript', url: 'https://satin-truffle-ac4.notion.site/Javascript-1d72ae802e29804596fbe823e86fa5a0' },
      { label: 'Qu\'est-ce que JS ?', url: 'https://www.notion.so/1d72ae802e298050b54df0ccebba21a5' },
      { label: 'Syntaxe & concepts', url: 'https://www.notion.so/1d72ae802e298049a83eed89d3a22e47' },
      { label: 'Variables', url: 'https://www.notion.so/1d72ae802e2980769052fff03bfee419' },
      { label: 'Types de données', url: 'https://www.notion.so/1d72ae802e29808f9a62dadf5479b520' },
    ],
  },
  S41: {
    title: '🌼 JS — Katas',
    bloc: 'JavaScript',
    notions: [
      'Katas repo JS : tests rouge→vert sur les notions de S40',
      'Pair tutoring : les plus avancés accompagnent les bloqués',
      'Débrief collectif J1 matin : remonter les blocages de S40',
    ],
    ia: 'Comparer sa solution avec la proposition IA — expliquer les différences',
    ia_mode: 'mixed',
    blocs_cda: ['BC01'],
    fondamentaux: 'Récupération active : se souvenir coûte et consolide — relire le cours ne vaut rien',
    links: [
      { label: '🌼 JavaScript', url: 'https://satin-truffle-ac4.notion.site/Javascript-1d72ae802e29804596fbe823e86fa5a0' },
      { label: 'Opérateurs conditionnels', url: 'https://www.notion.so/1d72ae802e2980389e60e63e3e7df3a4' },
      { label: 'Fonctions', url: 'https://www.notion.so/1d72ae802e29803584c6cb3a1a8b0466' },
      { label: 'Tableaux', url: 'https://www.notion.so/1d72ae802e2980408b7dc81d345c8d06' },
      { label: 'Méthodes des tableaux', url: 'https://www.notion.so/1d72ae802e2980808155dbef61cd293e' },
    ],
  },
  S42: {
    title: '🌼 JS avancé + 🐙 Git',
    bloc: 'JavaScript',
    extraBlocs: ['Git'],
    notions: [
      'JS : arrays, objets, destructuring, spread, méthodes fonctionnelles (map/filter/reduce)',
      'Fonctions pures vs effets de bord — quand un .map() mute silencieusement',
      'Git : clone, commit, branch, merge — leur code JS comme support concret à versionner',
    ],
    ia: 'Générer des messages de commit → évaluer leur qualité et leur utilité',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC03'],
    fondamentaux: 'Fonctions pures = pas d\'effet de bord = prédictibles · Git = graphe orienté acyclique — force-push sur main = catastrophe',
    links: [
      { label: '🐙 Git & GitHub', url: 'https://www.notion.so/Git-Github-3732ae802e298081a206e7f550efe9d6' },
      { label: '1️⃣ Git local', url: 'https://www.notion.so/3732ae802e298194b9c3dc49d0ceb550' },
    ],
  },
  S43: {
    title: '🐙 Git — Mini-projet GitHub Pages',
    bloc: 'Git',
    notions: [
      'Katas JS sur arrays/objets — consolidation S42',
      'Mini-projet : site HTML/CSS personnel versionné sur GitHub, déployé sur GitHub Pages (CI auto)',
      'PR et review croisée entre binômes — conventional commits',
    ],
    ia: 'L\'IA génère un README — évaluer la précision et la pertinence',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC03'],
    fondamentaux: 'Un historique Git propre se lit comme un journal — conventional commits + PR reviews = pratique pro dès le départ',
    links: [
      { label: '🐙 Git & GitHub', url: 'https://www.notion.so/Git-Github-3732ae802e298081a206e7f550efe9d6' },
      { label: '1️⃣ Git local', url: 'https://www.notion.so/3732ae802e298194b9c3dc49d0ceb550' },
    ],
  },
  S44: {
    title: '🎯 Conception V1 — Use case · Architecture · Métier',
    bloc: 'Vision métier',
    extraBlocs: ['Conception'],
    notions: [
      'J1-J2 : Vision Métier (interview client fictif, CDC e-shop, user stories) + Scrum/Kanban · Pour chaque user story : précondition (l\'utilisateur est-il connecté ?), invariant métier (un panier vide ne se commande pas, une quantité est toujours ≥ 1), embranchements (flux nominal / alternatif / erreur)',
      'J3 : Architecture N-tiers — schéma e-shop dessiné ensemble · chaque couche a ses invariants : le frontend ne touche jamais la BDD, l\'API ne retourne jamais de mot de passe',
      'J4-J5 : UML use case — acteurs, cas d\'utilisation, relations include/extend · exercice : pour chaque cas d\'utilisation, écrire les préconditions et postconditions avant de dessiner',
    ],
    ia: 'J1-J3 : sans IA — réflexion pure sur les invariants et la logique métier · J4-J5 : l\'IA génère un diagramme use case → évaluer si les embranchements métier sont bien représentés',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Un invariant métier = une règle qui ne doit jamais être violée, quelle que soit la couche · Modéliser les préconditions et embranchements dès la conception évite de les découvrir comme bugs en production',
    links: [],
  },
  S45: {
    title: '🎨 Conception V1 — Figma · Maquettes · XSS',
    bloc: 'Vision métier',
    extraBlocs: ['Fil rouge', 'Conception'],
    notions: [
      'J1-J3 : Figma — wireframes puis maquettes des écrans clés e-shop · Pour chaque écran : modéliser tous les états (vide, chargement, erreur, succès) — chaque état correspond à une précondition différente · les embranchements visuels doivent refléter les embranchements métier de S44',
      'J4-J5 : XSS découverte — attaquer une page HTML vulnérable, puis corriger · lien avec les invariants : "toute donnée utilisateur est hostile" = invariant de sécurité absolu',
    ],
    ia: 'J1-J3 : IA pour accélérer la production Figma · vérifier que les maquettes couvrent bien tous les embranchements identifiés en S44 · J4-J5 : l\'IA explique les vecteurs d\'attaque XSS',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'Un wireframe sans ses états d\'erreur est incomplet — les embranchements métier doivent être visibles dans les maquettes avant d\'être codés · XSS : invariant de sécurité — toute donnée utilisateur est hostile',
    links: [],
  },
  S46: {
    title: '🤖 IA fondamentaux + Sécurité',
    bloc: 'IA',
    notions: [
      'J1-J2 : LLMs, tokens, embeddings, hallucinations, éthique, RGPD — comprendre avant d\'utiliser',
      'J3 : XSS consolidation + OWASP Top 10 intro (rattrapage ALT qui ont raté S45)',
      'J4 : Prompt maïeutique vs délégation — pratique sur du code DOM/JS qu\'ils connaissent',
    ],
    ia: 'Séance fondatrice : anatomie d\'un LLM — comprendre pourquoi il confabule avant de lui faire confiance',
    ia_mode: 'theory',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'LLM = prédiction du token suivant — confabulation, biais, drift de contexte, injection de prompt sont des failles structurelles',
    links: [],
  },
  S47: {
    title: '🌼 JS async — fetch & Promises',
    bloc: 'JavaScript',
    notions: [
      'fetch, async/await, gestion d\'erreurs (.catch, try/catch), Promise.all',
      'Event loop mono-thread : ce qui le bloque (boucle synchrone infinie, JSON.parse massif)',
      'Katas : mini-app qui consomme une API publique — lecture doc MDN en anglais imposée',
    ],
    ia: 'Déboguer du code async avec l\'IA — identifier les race conditions et les unhandled rejections',
    ia_mode: 'copilot',
    blocs_cda: ['BC01'],
    fondamentaux: 'JS est mono-thread — l\'event loop ne bloque pas, mais certaines ops bloquent l\'event loop : les reconnaître évite les freezes prod',
    links: [
      { label: '🌼 JavaScript', url: 'https://satin-truffle-ac4.notion.site/Javascript-1d72ae802e29804596fbe823e86fa5a0' },
      { label: 'Boucles', url: 'https://www.notion.so/1d72ae802e2980b881d6c414ea119ec1' },
      { label: 'Objets', url: 'https://www.notion.so/1d72ae802e2980e8b3fff6f834f6b7cd' },
      { label: 'DOM', url: 'https://www.notion.so/1d72ae802e298060acc2f8e22d0915de' },
    ],
  },
  S48: {
    title: '🟦 TypeScript + JS Bundle',
    bloc: 'TypeScript',
    notions: [
      'Types de base, interfaces, type guards, migration d\'un module JS → TS strict',
      'TS disparaît au runtime — ce qu\'il ne protège pas (erreurs réseau, JSON externe, any qui contamine)',
      'JS bundle intro : qu\'est-ce qu\'un bundler, build pipeline, tree shaking, source maps, prod vs dev',
    ],
    ia: 'J1-J2 : sans IA — ancrer le système de types · J3-J5 : l\'IA génère du TS typé → repérer les dérives (any implicite)',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'TS disparaît au runtime — fausse sécurité si on ne comprend pas cette limite · Bundle = votre code ≠ ce qui arrive au browser',
    links: [{ label: '🟦 TypeScript', url: 'https://satin-truffle-ac4.notion.site/Typescript-25d2ae802e2980a79ea5e8a48349fb33' }],
  },
  S49: {
    title: '🟦 TS katas + Modélisation fil rouge',
    bloc: 'TypeScript',
    extraBlocs: ['Fil rouge'],
    notions: [
      'Katas TypeScript — types avancés, utility types (Partial, Pick, Omit)',
      'UML diagramme de séquence : modéliser 2 flux critiques e-shop (authentification JWT, ajout panier) — échanges entre couches Frontend / API / BDD',
      'Angular CLI : install + observation du premier composant généré (lecture guidée, pas de cours)',
    ],
    ia: 'L\'IA génère les interfaces TS pour le modèle e-shop → vérifier la cohérence avec le schéma BDD',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'Modéliser avant de coder — le diagramme de séquence expose les dépendances cachées entre couches avant qu\'elles ne deviennent des bugs d\'intégration',
    links: [{ label: '🟦 TypeScript', url: 'https://satin-truffle-ac4.notion.site/Typescript-25d2ae802e2980a79ea5e8a48349fb33' }],
  },
  S50: {
    title: '🛡️ Angular — Fondamentaux framework',
    bloc: 'Angular',
    notions: [
      'Pipeline Angular (TS→JS→bundle→browser) · SSOT & flux unidirectionnel — pourquoi avant comment',
      '@Component, binding, @Input/@Output — comprendre le mécanisme avant de l\'utiliser',
      'Signals : modèle mental "source de vérité réactive" ancré dès le départ (pas en fin de parcours)',
    ],
    ia: 'J1-J2 : sans IA — comprendre le pipeline et le binding · J3-J5 : l\'IA génère un composant → analyser la structure',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'SSOT = source unique de vérité — état dupliqué = bugs silencieux · Signals = réactivité fine sans zone.js · Flux unidirectionnel = prédictibilité et debugging',
    links: [
      { label: '🛡️ Angular', url: 'https://satin-truffle-ac4.notion.site/Angular-2092ae802e298032b6e6f8db22315706' },
      { label: 'Les Composants', url: 'https://www.notion.so/2092ae802e298034b8bcff5ca18a33ef' },
      { label: 'Les Templates', url: 'https://www.notion.so/2092ae802e298030857de758641e5ffc' },
    ],
  },
  S51: {
    title: '🛡️ Angular — Démarrage fil rouge e-shop',
    bloc: 'Angular',
    extraBlocs: ['Fil rouge'],
    notions: [
      'Setup repo fil rouge e-shop : architecture décidée, conventions posées, CI configurée',
      'Premier composant réel sur leur propre projet — pas un kata, pas un tuto',
      'Pas de nouveau concept Angular : consolider @Component + Signals sur du vrai code',
    ],
    ia: 'L\'IA aide à scaffolder la structure du projet — l\'apprenant valide chaque décision d\'architecture',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Un projet réel n\'est pas un kata — les décisions d\'architecture ont des conséquences : les poser maintenant, pas à mi-parcours',
    links: [
      { label: '🛡️ Angular', url: 'https://satin-truffle-ac4.notion.site/Angular-2092ae802e298032b6e6f8db22315706' },
      { label: 'Signals', url: 'https://www.notion.so/2622ae802e2980d496d3c155dee2b445' },
    ],
  },
  S1: {
    title: '🛡️ Angular — Router · Services · HttpClient',
    bloc: 'Angular',
    notions: [
      'Router (routes, RouterLink, ActivatedRoute, guards) + Formulaires réactifs (FormGroup, FormControl, Validators)',
      'Services @Injectable, HttpClient (GET/POST/PUT/DELETE) — injection de dépendances : le framework gère les instances',
    ],
    ia: 'J1-J2 : sans IA (routing + formulaires) · J3-J5 : l\'IA génère les calls HttpClient → analyser les types de retour',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'DI = singleton géré par le framework · Routing client-side ≠ routing serveur (History API, 404 nginx) · HttpClient = abstraction typée sur fetch',
    links: [
      { label: '🛡️ Angular', url: 'https://satin-truffle-ac4.notion.site/Angular-2092ae802e298032b6e6f8db22315706' },
      { label: 'Le Router', url: 'https://www.notion.so/26f2ae802e298009ac6bdda6ae01dc94' },
      { label: 'Les Formulaires', url: 'https://www.notion.so/2702ae802e298018a7e9db10423fa1d3' },
      { label: 'Les Services', url: 'https://www.notion.so/2092ae802e2980b48156f021815221dd' },
      { label: 'Les requêtes HTTP', url: 'https://www.notion.so/2092ae802e2980438132eeb436479620' },
    ],
  },
  S2: {
    title: '🛡️ Angular — Katas fil rouge (Router + Services)',
    bloc: 'Angular',
    extraBlocs: ['Fil rouge'],
    notions: [
      'Application des notions sur le projet e-shop : routes, guards, formulaire de connexion/inscription',
      'Services Angular : pattern Repository, state management simple avec Signals',
      'Appels HTTP e-shop : liste produits, panier — calls réels (mock) vers l\'API Spring Boot à venir',
    ],
    ia: 'L\'IA génère un service complet → analyser la structure, le pattern, les edge cases',
    ia_mode: 'copilot',
    blocs_cda: ['BC01'],
    fondamentaux: 'Un service @Injectable est un singleton — toute mutation d\'état dans un service affecte tous les composants qui l\'injectent',
    links: [
      { label: '🛡️ Angular', url: 'https://satin-truffle-ac4.notion.site/Angular-2092ae802e298032b6e6f8db22315706' },
      { label: 'Les Services', url: 'https://www.notion.so/2092ae802e2980b48156f021815221dd' },
      { label: 'Signals', url: 'https://www.notion.so/2622ae802e2980d496d3c155dee2b445' },
    ],
  },
  S3: {
    title: '☕ Java — Syntaxe + POO + Exceptions',
    bloc: 'Java',
    notions: [
      'J1-J2 : Syntaxe Java (JDK, types primitifs, méthodes, boucles, tableaux) — Hello World en 10min, le reste en katas',
      'J3-J4 : POO (classes, héritage vs composition, interfaces, exceptions) — early return > catch silencieux',
      'J5 : JUnit 5 intro (@Test, assertions, @BeforeEach) — premier test unitaire réel sur du code qu\'ils viennent d\'écrire',
    ],
    ia: 'L\'IA explique les stack traces Java · L\'IA génère des tests JUnit → vérifier la pertinence des assertions',
    ia_mode: 'mixed',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'Java = compilé, fortement typé — erreur de type à la compilation, pas au runtime · Héritage vs composition — fragile base class problem · Exceptions : early return + exception typée > catch silencieux',
    links: [
      { label: '☕ Java', url: 'https://satin-truffle-ac4.notion.site/Java-1f82ae802e2980f49405d0b5c5c311c6' },
      { label: 'JDK', url: 'https://www.notion.so/1f82ae802e29806188f1fbc5a483891f' },
      { label: 'Syntaxe & algo', url: 'https://www.notion.so/1f82ae802e298032b68dfa449bcd50be' },
      { label: 'Variables', url: 'https://www.notion.so/1f82ae802e298006a308dcf3d64ebc73' },
      { label: 'POO bases', url: 'https://www.notion.so/1fa2ae802e29800ba078c4c848702b55' },
      { label: 'Héritage', url: 'https://www.notion.so/1f82ae802e2980fb8edbe864030c1284' },
      { label: 'Interfaces', url: 'https://www.notion.so/1f82ae802e2980c7ada0ed11d62b5f7c' },
    ],
  },
  S4: {
    title: '☕ Java — Katas + Streams + JUnit',
    bloc: 'Java',
    extraBlocs: ['Conception'],
    notions: [
      'Katas Java approfondis : collections, méthodes complexes, conditions imbriquées',
      'Streams API : filter, map, collect, Optional — fonctionnement interne et cas d\'usage réels',
      'Conception Passe 2 — Diagramme de classes V1 : entités e-shop (Produit, Commande, Utilisateur), relations, cardinalités · invariants de classe (un Produit sans prix est invalide dès la construction) · préconditions des méthodes métier · les classes Java qu\'ils viennent d\'écrire deviennent le modèle',
    ],
    ia: 'L\'IA génère des tests JUnit → vérifier la couverture et repérer les assertions superficielles',
    ia_mode: 'mixed',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'Tester via l\'API publique, jamais les méthodes privées · Diagramme de classes = contrat structurel — les invariants y sont lisibles avant même d\'ouvrir le code · un constructeur qui laisse passer un objet invalide est une faille de conception',
    links: [
      { label: '☕ Java', url: 'https://satin-truffle-ac4.notion.site/Java-1f82ae802e2980f49405d0b5c5c311c6' },
      { label: 'Tableaux & itérations', url: 'https://www.notion.so/1f82ae802e2980769004f379d4443c34' },
      { label: 'ArrayList', url: 'https://www.notion.so/1f82ae802e29805ebf2ad1599ee68aee' },
    ],
  },
  S5: {
    title: '🗄️ SQL — Modélisation + Requêtes + NoSQL concept',
    bloc: 'SQL',
    extraBlocs: ['Conception'],
    notions: [
      'J1-J2 : Conception Passe 2 suite — du diagramme de classes (S4) au MLD : traduction des relations en tables, cardinalités → clés étrangères · contraintes SQL = invariants BDD (NOT NULL, UNIQUE, FK — un enregistrement sans contrainte est une promesse sans garantie)',
      '🕵️ J3 : SQL Murder Mystery — katas en contexte narratif (agrégats, COUNT, GROUP BY, HAVING, sous-requêtes)',
      'J4 : NoSQL concept (1h) — document store vs relationnel, cas d\'usage MongoDB — pas d\'implémentation · J4-J5 : index, EXPLAIN, injections SQL',
    ],
    ia: 'L\'IA explique un plan d\'exécution SQL (EXPLAIN) et génère des requêtes → repérer les injections potentielles',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02'],
    fondamentaux: 'Un schéma BDD est une décision d\'architecture — modifier une colonne en prod coûte cher · Injection SQL = faille #1 OWASP · NoSQL = choix selon le cas d\'usage, pas un remplacement',
    links: [],
  },
  S6: {
    title: '🗄️ SQL katas + 🍃 Spring Boot preview',
    bloc: 'SQL',
    extraBlocs: ['Spring Boot'],
    notions: [
      'SQL katas consolidation : requêtes complexes, sous-requêtes, optimisation — sur le schéma e-shop réel',
      'Java Streams + JUnit approfondissement : filter, map, collect, Optional',
      'Spring Boot preview : lecture doc officielle en anglais (Servlet, IoC) — fondamentaux avant le code',
    ],
    ia: 'L\'IA explique les différences entre INNER JOIN, LEFT JOIN et FULL OUTER JOIN avec des exemples',
    ia_mode: 'mixed',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'SQL Murder Mystery : apprendre en contexte narratif — la motivation est la meilleure charge cognitive',
    links: [],
  },
  S7: {
    title: '🍃 Spring Boot 1 — JPA + REST + Sécurité',
    bloc: 'Spring Boot',
    notions: [
      'JPA : @Entity, @Repository, Spring Data, CRUD endpoints REST — pipeline IoC complet',
      'Architecture Spring : IoC container, beans, proxy, N+1 queries (faille classique silencieuse)',
      'Sécurité : CORS, HTTPS, variables d\'env jamais en dur · schéma BDD e-shop formalisé (script SQL)',
    ],
    ia: 'L\'IA génère une entité JPA + repository → vérifier les annotations et détecter les N+1 potentiels',
    ia_mode: 'mixed',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Spring = conteneur IoC — les beans sont gérés par le framework · N+1 query = SELECT dans une boucle = catastrophe en production',
    links: [
      { label: '🍃 Spring Boot', url: 'https://satin-truffle-ac4.notion.site/Spring-Boot-28c2ae802e29802d9edecb8920734da3' },
      { label: 'Introduction au backend', url: 'https://www.notion.so/28d2ae802e29802b9dd8f377f61029ec' },
      { label: 'Introduction Spring Boot', url: 'https://www.notion.so/28d2ae802e298010832dee900e0bf0ab' },
      { label: 'Persistance JPA', url: 'https://www.notion.so/2932ae802e29805fb27bc25ece0054b6' },
    ],
  },
  S8: {
    title: '🍃 Spring Boot — Katas + Plan de tests',
    bloc: 'Spring Boot',
    extraBlocs: ['Fil rouge', 'Conception'],
    notions: [
      'Katas Spring Boot : couche service, @Service, séparation des responsabilités, @ExceptionHandler · Design patterns nommés : Repository (accès données), Strategy (comportement interchangeable) — les reconnaître dans le code Spring pour savoir les argumenter au jury',
      'Plan de tests formalisé : template, jeu d\'essai, données attendues vs obtenues — à remplir pour l\'e-shop',
      'Conception Passe 3 — Diagramme de séquence : modéliser 2 flux critiques e-shop (auth JWT, ajout panier) · fragments combinés UML : alt (embranchements), opt (optionnel), loop — les préconditions et invariants de la Passe 1 deviennent des fragments de séquence formels',
    ],
    ia: 'L\'IA structure la couche service — l\'apprenant valide la séparation des responsabilités',
    ia_mode: 'copilot',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'Plan de tests = contrat de confiance · Diagramme de séquence : chaque fragment alt est un embranchement métier — si tu ne peux pas le dessiner, tu ne l\'as pas compris · Design patterns = vocabulaire partagé pour argumenter une décision d\'architecture · @ExceptionHandler global : 4xx expose le message (safe), 5xx message générique (sécurité)',
    links: [
      { label: '🍃 Spring Boot', url: 'https://satin-truffle-ac4.notion.site/Spring-Boot-28c2ae802e29802d9edecb8920734da3' },
      { label: 'Exposition REST', url: 'https://www.notion.so/28d2ae802e29800ba606db8dc36ea329' },
      { label: 'Exceptions', url: 'https://www.notion.so/2942ae802e2980259bffd960b7b654e8' },
      { label: 'Métier', url: 'https://www.notion.so/2952ae802e29800aa988e96aa1d44011' },
      { label: 'Tests', url: 'https://www.notion.so/2972ae802e2980f59da6d12372e5eeae' },
    ],
  },
  S9: {
    title: '🍃 Spring Security + JWT + 🐳 Docker',
    bloc: 'Spring Boot',
    extraBlocs: ['CI/CD', 'Fil rouge'],
    notions: [
      'Spring Security : filtres, JWT (claims signés, pas chiffrés — ce qu\'on peut lire, ce qu\'on ne doit pas y mettre)',
      'bcrypt, hachage mots de passe, rotation des tokens, gestion de l\'expiration',
      'Docker intro : Dockerfile, docker-compose Spring Boot + PostgreSQL — isolation reproductible',
    ],
    ia: '🤖 Ollama : appel LLM local depuis Spring Boot (feature e-shop IA) · IA génère le filtre JWT → l\'apprenant comprend chaque ligne',
    ia_mode: 'mixed',
    blocs_cda: ['BC02', 'BC03'],
    fondamentaux: 'JWT = claims signés, pas chiffrés — lire le payload avec jwt.io · bcrypt = irréversible par design · Docker = reproductibilité, pas de "ça marche sur mon poste"',
    links: [
      { label: '🍃 Spring Boot', url: 'https://satin-truffle-ac4.notion.site/Spring-Boot-28c2ae802e29802d9edecb8920734da3' },
      { label: 'Authentification JWT', url: 'https://www.notion.so/2952ae802e29801987a2c63850269da7' },
      { label: '🐳 Docker', url: 'https://satin-truffle-ac4.notion.site/Docker-2852ae802e298038b5bbc1441663555c' },
      { label: 'Docker + SpringBoot', url: 'https://satin-truffle-ac4.notion.site/Docker-SpringBoot-2982ae802e2980e5bd1ff769c1bd0477' },
    ],
  },
  S10: {
    title: '⚙️ CI/CD Fullstack + Anglais certif',
    bloc: 'CI/CD',
    extraBlocs: ['Fil rouge', 'Conception'],
    notions: [
      'GitHub Actions fullstack : lint, tests, build Angular + Spring Boot, déploiement VPS',
      'nginx reverse proxy, HTTPS Let\'s Encrypt, variables secrets GitHub, docker-compose prod · Livrable fil rouge obligatoire : diagramme de déploiement (VPS, nginx, containers, BDD) — artefact attendu dans le dossier de projet CDA',
      'Prépa questionnaire anglais B1 (format certif : QCM + 2 questions ouvertes répondues en anglais)',
    ],
    ia: 'L\'IA génère le workflow GitHub Actions · L\'IA simule le questionnaire anglais RNCP',
    ia_mode: 'delegation',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Un pipeline = automatisation de la confiance — drift, secrets en clair, déploiement manuel = les 3 failles classiques de la mise en prod',
    links: [
      { label: '🤖 CI-CD', url: 'https://satin-truffle-ac4.notion.site/CI-CD-2862ae802e298087b982f578be8782b7' },
      { label: 'CI + Angular', url: 'https://satin-truffle-ac4.notion.site/CI-Angular-2862ae802e2980389270d94059214d69' },
      { label: 'CD + Angular', url: 'https://satin-truffle-ac4.notion.site/CD-Angular-2862ae802e29806aad19d2e25670febe' },
      { label: 'CI + SpringBoot', url: 'https://satin-truffle-ac4.notion.site/CI-SpringBoot-2982ae802e29802bbb13dbf94d016724' },
      { label: 'CD + SpringBoot', url: 'https://satin-truffle-ac4.notion.site/CD-SpringBoot-2982ae802e2980e19a11cbace23a5082' },
      { label: '🐳 Docker', url: 'https://satin-truffle-ac4.notion.site/Docker-2852ae802e298038b5bbc1441663555c' },
    ],
  },
  S21: {
    title: '🔄 Reprise post-stage',
    bloc: 'Certification',
    notions: [
      'Diagnostic technique post-stage : ce qui a été pratiqué, ce qui a été oublié, ce qui surprend',
      'Remobilisation : daily standup repris, veille reprise, repo fil rouge relu',
      'Points blocages stage — ce qu\'ils auraient eu besoin de savoir',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Le stage révèle les vraies lacunes — ce diagnostic oriente les 3 semaines de préparation',
    links: [],
  },
  S22: {
    title: '📋 Dossier + Simulation jury',
    bloc: 'Certification',
    notions: [
      'Finalisation dossier de projet (rédigé pendant le stage) — mapping compétences RNCP par CCP',
      'Relecture croisée · corrections de fond · structure 40-60 pages vérifiée',
      'Simulation jury partielle · entraînement anglais certif session 1 (QCM + ouvertes)',
    ],
    ia: 'L\'IA relit le dossier et identifie les zones faibles · L\'IA joue le rôle du jury en anglais',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Rigueur documentaire : un dossier bien structuré raconte une histoire de montée en compétences — pas une liste de tâches',
    links: [],
  },
  S23: {
    title: '🎤 Simulation jury + Anglais certif',
    bloc: 'Certification',
    notions: [
      'Simulation jury complète en binôme : 40min présentation + 45min entretien technique simulé',
      'Révision BC01/BC02/BC03 — points faibles identifiés en S22 traités en priorité',
      'Questionnaire anglais session 2 : 2 QCM + 2 questions ouvertes répondues en anglais (format certif exact)',
    ],
    ia: 'L\'IA joue le rôle du jury : questions techniques et transversales · simule le questionnaire anglais RNCP',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Posture professionnelle : argumenter une décision d\'architecture vaut mieux que réciter une définition',
    links: [],
  },
  S24: {
    title: '🎓 Certification RNCP — TP',
    bloc: 'Certification',
    notions: [
      'Passage devant le jury RNCP37873',
      'Présentation dossier de projet',
      'Épreuve orale — semaine du 14 juin',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Validation des compétences CDA',
    links: [],
  },
  S34: {
    title: '🏫 Retour en centre — Alternants',
    bloc: 'Alternants',
    notions: [
      'Retour en centre (23–27 août) — alternants uniquement',
      'Contenu à définir',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: [],
    fondamentaux: 'À préciser',
    links: [],
  },
  S36: {
    title: '📋 Relecture des dossiers — Alternants',
    bloc: 'Certification',
    notions: [
      'Alternants uniquement (6–10 sept) — TP déjà terminés',
      'Relecture croisée des dossiers de projet',
      'Corrections finales · points de vigilance jury',
    ],
    ia: 'L\'IA identifie les zones faibles du dossier',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Synthèse, rigueur documentaire',
    links: [],
  },
  S37: {
    title: '🏢 Alternants en entreprise',
    bloc: 'Alternants',
    notions: [
      'Semaine entreprise (13–17 sept)',
      'À confirmer — peut varier selon les contrats',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: [],
    fondamentaux: '',
    links: [],
  },
  S38: {
    title: '🎤 Préparation aux épreuves',
    bloc: 'Certification',
    notions: [
      'Retour en centre (20–24 sept)',
      'Simulation jury en binôme · entraînement oral',
      'Révision BC01 · BC02 · BC03 · posture professionnelle',
    ],
    ia: 'L\'IA simule les questions du jury RNCP',
    ia_mode: 'copilot',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Argumentation technique, posture pro',
    links: [],
  },
  S39b: {
    title: '🎓 Certification RNCP — Alternants',
    bloc: 'Certification',
    notions: [
      'Passage devant le jury RNCP37873',
      'Présentation dossier entreprise ou portfolio',
      'Épreuve orale — 27 sept – 1er oct (à confirmer)',
    ],
    ia: '',
    ia_mode: 'none',
    blocs_cda: ['BC01', 'BC02', 'BC03'],
    fondamentaux: 'Validation des compétences CDA',
    links: [],
  },
}
