export interface ElèveEvaluation {
  prenom: string
  nom: string
  projet: string
  stack: string
  notes: {
    CCP1: string
    CCP2: string
    CCP3: string
  }
  resume: string
  pointsForts: string[]
  anglesMorts: string[]
  moyen_ameliorer: string[]
  questionsCCP1: string[]
  questionsCCP2: string[]
  questionsCCP3: string[]
  verdict: string
  alerte?: string
}

export const ELEVES_EVALUATIONS: ElèveEvaluation[] = [
  {
    prenom: 'Ashley',
    nom: 'Labory',
    projet: 'Jokeur (formulaires dynamiques + export PDF/Excel, 115 p. + 25 annexes)',
    stack: 'Angular 21 SSR + Express / Java 21 Spring Boot 4 / MySQL',
    notes: {
      CCP1: 'excellent',
      CCP2: 'excellent (avec réserve)',
      CCP3: 'bien à excellent',
    },
    resume: 'Jokeur, équipe de 4, 9 semaines : suivi médical animal (constantes, symptômes, traitements, vaccins, RDV, exports PDF/XLSX). Docker multi-stage, CI/CD GitHub Actions, VPS OVH, Traefik, staging + prod.',
    pointsForts: [
      'Structure quasi exhaustive vs REAC : sécurité, RGPD, RGAA avec Lighthouse 96/100',
      'Anglais (12.3 traduction refactoring.guru)',
      'Sécurité argumentée et honnête : BCrypt+sel, JWT typé, CORS whitelist, CSRF justifié',
      'Résolution de problème en démarche scientifique (bug Jackson AnimalType)',
      'Annexes de grande qualité',
      'Choix systématiquement justifiés par comparaison',
      'Veille datée et concrète avec impact sur les choix du projet',
    ],
    anglesMorts: [
      'Script SQL / migrations versionnées (Flyway/Liquibase) : absents ; ddl-auto: update',
      'Jeu d\'essai formalisé (entrées/attendu/obtenu/écarts) : absent en tant que tableau',
      'Veille vulnérabilités : techno seulement, pas d\'OWASP/CVE/Dependabot',
      'Sauvegarde/restauration MySQL : rien',
      'NoSQL : argumenté en creux, non pratiqué',
      'Pas de Gantt ni suivi prévu/réalisé chiffré',
      'Use cases très réduits (5 cas)',
      'Monitoring limité au dashboard Traefik',
      'RGPD : données animaux ne sont pas personnelles (fragile juridiquement)',
    ],
    moyen_ameliorer: [
      'Expression des besoins sommaire (contraintes/livrables non formalisés)',
      'CORS en dur dans le code',
      'Mappers tout en static ; @Transactional classe sans discussion readOnly',
      'Liste manuelle des routes dans SecurityConfig : maintenance risquée',
      '115 p. de corps vs 40-60 max REAC : le défaut matériel le plus important',
      'Qui a fait quoi pas toujours précisé (sécurité Spring, CI/CD)',
    ],
    questionsCCP1: [
      'JWT en localStorage : scénario d\'attaque XSS concret ; passage en cookie HttpOnly et impact sur le CSRF désactivé ?',
      'DynamicFormComponent mélange signals et valueChanges+take(1) : double soumission d\'une erreur serveur ? Fuites d\'abonnement ?',
      'Réécrivez buildDynamicForm au tableau et justifiez chaque validateur',
      'Un conflit Git concret et ce que votre politique de branches imposait ?',
    ],
    questionsCCP2: [
      'ddl-auto: update : risques en prod ? Versionner l\'ajout d\'une colonne NOT NULL sur health_record sans perte ?',
      'SQL généré par existsByTattoo ; SQL natif équivalent de findDashboardDtosByUserId avec jointure explicite',
      'PetBreed en enum Java vs table de référence : ajout d\'une race sans redéploiement ?',
      'Un cas NoSQL pertinent dans Jokeur (ex. flux RSS) et accès depuis Spring ?',
      'GET /health-records/{id} : comment empêcher l\'utilisateur A de lire le carnet de B (IDOR) ? Montrez le code',
    ],
    questionsCCP3: [
      'Jeu d\'essai de l\'export PDF au format REAC + un écart traité',
      'docker compose down && up : indisponibilité ? Déploiement sans coupure ? Rollback d\'une image défectueuse ?',
      'Sauvegarde MySQL de prod et test de restauration ? Veille CVE (Spring, Angular, jjwt) ?',
    ],
    verdict: 'Niveau nettement supérieur aux attentes — admission sans réserve visée, sous deux conditions : ramener le corps au format REAC (40-60 p.) et combler à l\'oral script SQL/migrations, jeu d\'essai, veille vulnérabilités, contrôle d\'accès par propriétaire.',
    alerte: '115 pages : dépasse le gabarit REAC (40-60 p.)',
  },
  {
    prenom: 'Henri',
    nom: 'Rosmann Secondi',
    projet: 'TDAppy (dossier NON TERMINÉ, 72 p.)',
    stack: 'Angular (signals, stores, façades) / Spring Boot (JWT, JPA, MySQL)',
    notes: {
      CCP1: 'bien',
      CCP2: 'bien',
      CCP3: 'bien',
    },
    resume: 'TDAppy, équipe de 4, 9 semaines : annuaire CMP/CMPP via API FHIR + Géoplateforme avec carte Leaflet, auto-test, forum modéré, pomodoro/tâches. Docker, CI/CD GitHub Actions, VPS OVH, Traefik, 3 environnements.',
    pointsForts: [
      'Architecture front Angular moderne maîtrisée avec schémas de flux numérotés',
      'CI/CD réelle, URLs prod/staging publiques — vraie mise en production',
      'Sécurité concrète : SecurityFilterChain commenté, schéma filtre JWT, Bucket4j, Fail2ban',
      'Intégration de 2 API externes (FHIR + Géoplateforme) avec fusion de données',
      'RGPD/RGAA/RGE traités',
      'Posture de concepteur (compromis discutés partout)',
    ],
    anglesMorts: [
      'Liste des compétences REAC : absente (1er élément du plan imposé)',
      'Cahier des charges formalisé : absent',
      'NoSQL : aucune trace',
      'Jeu d\'essai : absent',
      'Veille vulnérabilités : non traitée',
      'Script SQL : non fourni',
      'Anglais B1 : aucune mention',
      'Diagrammes de séquence : un seul, trivial',
      'Planning/écarts : absent',
      'Sections inachevées à finaliser',
    ],
    moyen_ameliorer: [
      'Use case unique confus, formalisme douteux',
      'Pas de plan de tests (matrice) ni résultats chiffrés',
      'JWT localStorage assumé mais argumentation faible ; CSRF en une phrase',
      'Config Spring en prod (ddl-auto ?) vague',
      'Contribution individuelle indiscernable',
      'Orthographe (« Intégration continu », « stagging »…)',
    ],
    questionsCCP1: [
      'JWT en localStorage : risques XSS, pourquoi pas cookie HttpOnly + CSRF ? Choix aujourd\'hui ?',
      'OAuth2LoginSuccessHandler crée un utilisateur avec mot de passe UUID : que se passe-t-il si connexion classique ensuite ?',
      'Qu\'avez-VOUS développé personnellement ? Un composant dont vous êtes l\'unique auteur ?',
      'Un sprint en retard : détection et traitement ?',
      'Pourquoi --skip-tests à la génération ? Comment décidez-vous ce qui mérite un test ?',
    ],
    questionsCCP2: [
      'Où introduire du NoSQL dans TDAppy, avec quel moteur ?',
      'Diagramme de séquence au tableau : authentification avec JWT expiré (interceptor + filtre)',
      'Table Report avec id_user et id_user_1 : expliquez ; intégrité référentielle à la suppression (RGPD) ?',
      'cascade=ALL + orphanRemoval : dangers ; pourquoi ne pas l\'utiliser pour deleteReply ?',
      'Cas réel où le SQL natif était nécessaire ; risque d\'injection et protection @Param ?',
    ],
    questionsCCP3: [
      'Jeu d\'essai de la recherche d\'annuaire : présentez-le maintenant',
      'Une vulnérabilité découverte par votre veille pendant le projet ? Outillage (Dependabot, Dependency-Check) ?',
      'Déploiement SSH qui échoue à mi-chemin : rollback ? Sauvegarde/restauration de la base ?',
    ],
    verdict: 'Prometteur et techniquement au-dessus des attendus (architecture, sécurité, DevOps), mais à finaliser impérativement (annexes vides, compétences, jeu d\'essai, veille, UML) et à clarifier sur la contribution individuelle.',
    alerte: 'Dossier NON TERMINÉ : placeholders vides, annexes vides',
  },
  {
    prenom: 'Johanna',
    nom: 'Keïta (Jphana)',
    projet: 'TDAppy (Angular / Spring Boot / MySQL, ~92 p. + 26 annexes)',
    stack: 'Angular (standalone, Signals, Facade/Store/API) / Spring Boot / MySQL',
    notes: {
      CCP1: 'bien',
      CCP2: 'bien',
      CCP3: 'bien',
    },
    resume: 'TDAppy : forum, questionnaire d\'orientation, annuaire CMP cartographié, pomodoro, to-do. Front Angular, back Spring Boot en couches, 8 sprits Agile/Trello/Git flow, CI/CD GitHub Actions, Docker, OVH/Traefik.',
    pointsForts: [
      'Feature « création de topic » racontée de A à Z front→back→BDD avec code commenté',
      'Architecture front avancée et back propre (DTO records + Jakarta Validation, factory)',
      'Encadrés « Choix retenu / Alternatives » à chaque chapitre',
      'MCD→MLD→MPD complet',
      'Tests réels en annexes (pas seulement déclarés)',
      'RGPD bien traité pour un domaine santé (minimisation, hébergement UE)',
    ],
    anglesMorts: [
      'Diagramme de séquence absent (exigé par le plan REAC)',
      'Jeu d\'essai formalisé absent',
      'Script SQL non fourni',
      'Veille sécurité non spécifique',
      'NoSQL non traité',
      'Anglais : aucune trace',
      '~92 p. : très au-dessus du gabarit 40-60 p.',
      'Plan de tests en tant que document : inexistant',
      'Éco-conception non mentionnée',
      'Expression des besoins initiale légère',
    ],
    moyen_ameliorer: [
      'Sécurité déclarative : aucune capture SecurityFilterChain/filtre JWT',
      'Contradiction CSRF/stateless à clarifier avant l\'oral',
      'Flou réalisé vs prévu (rate limiting, Auth0)',
      'Incohérences solo/équipe',
      'Couverture de tests sans chiffre',
      'Accessibilité affirmée sans audit',
      'Fautes récurrentes',
    ],
    questionsCCP1: [
      'CSRF activé en sessions STATELESS avec JWT : pourquoi ? Que recommande-t-on ?',
      'Où et comment le forum est-il sanitisé contre le XSS ?',
      'Rate limiting « prévu » : qu\'est-ce qui est réellement en prod ?',
      'Stockage du JWT côté front : risques localStorage vs cookie HttpOnly ?',
      'TopicEntity.create() + TopicRules : pourquoi cette double validation ?',
    ],
    questionsCCP2: [
      'Dessinez le diagramme de séquence de la création de topic au tableau',
      'Script SQL de création ? Migrations entre environnements ?',
      'TopicRequestDTO contient l\'userId envoyé par le front : risque ?',
      'CascadeType.ALL + orphanRemoval sur les réponses : conséquences ?',
      'Un cas où MongoDB aurait été plus pertinent dans TDAppy ?',
    ],
    questionsCCP3: [
      'Jeu d\'essai de la création de topic : entrées, attendu, obtenu, un écart analysé',
      'Une vulnérabilité concrète (CVE, OWASP) identifiée et ce que vous avez vérifié ?',
      'Tests qui échouent après merge vers production : rollback ?',
    ],
    verdict: 'Solide et au-dessus des attendus sur la réalisation technique et le DevOps ; validation probable, mais corriger avant l\'oral : diagramme de séquence, jeu d\'essai, script SQL, format trop long.',
    alerte: '~92 pages : dépasse le gabarit REAC (40-60 p.)',
  },
  {
    prenom: 'Kévin',
    nom: 'Larvor',
    projet: 'TDAppy (plateforme TDAH/DYS, 70 p. + 22 p. annexes)',
    stack: 'Angular / Spring Boot / MySQL, OAuth2 Google',
    notes: {
      CCP1: 'excellent',
      CCP2: 'excellent',
      CCP3: 'excellent',
    },
    resume: 'TDAppy, équipe de 4, 10 semaines : forum, recherche CMP (API FHIR/Geopf), outils (pomodoro, to-do), tests ASRS/Vanderbilt, dashboard admin. 3 dépôts, VPS OVH, Docker/Traefik, CI/CD staging + prod. Contributions : authentification, dashboard admin, questionnaire, Scrum Master.',
    pointsForts: [
      'Environnement très complet (p.24-27, 35-37)',
      'UI avec ARIA/responsive et code réel',
      'smart/dumb + façade + store signals',
      'Spring Security/BCrypt/AuthRules',
      'Sondage, user stories, use cases, diagrammes de séquence',
      'Pyramide complète TU/intégration/Cypress',
      'Sécurité en profondeur : SQLi, XSS/DomSanitizer, Bucket4j, CSRF, TLS, Fail2Ban',
      'CI/CD réelle et démontrée',
      'Architecture front mature',
      'Conformité rare : RGPD, RGAA, RGE',
      'Choix techniques systématiquement argumentés',
      'Modélisation complète Merise + UML',
    ],
    anglesMorts: [
      'Jeu d\'essai ABSENT (entrées/attendu/obtenu/écarts)',
      'Plan de tests formalisé absent',
      'Veille vulnérabilités quasi absente',
      'Anglais B1 : aucune trace',
      'Gestion de projet : pas de Gantt/jalons',
      'Script SQL et sauvegarde absents',
      'Longues sections sans extraits de code',
      'Contribution perso vs groupe pas toujours nette',
    ],
    moyen_ameliorer: [
      'Tableau de compétences vague',
      'Justification MySQL inexacte',
      'Accessibilité : pas de résultats d\'audit chiffrés',
      'RGPD : pas de registre, pas de politique de confidentialité',
      'Use cases : formalisme include/extend discutable',
      'IDOR potentiel : DELETE /user/me/{id} avec id en URL',
      'Vérification post-déploiement manuelle',
    ],
    questionsCCP1: [
      'DELETE /user/me/{id} avec id en URL : quel risque IDOR, quelle correction ?',
      'JWT en localStorage + CSRF désactivé : que faut-il changer ?',
      'banUser lève une RuntimeException générique : pourquoi ?',
      'Votre rôle de Scrum Master sprint par sprint ?',
      'Suivi vs planning initial : un retard identifié ?',
    ],
    questionsCCP2: [
      'Soft delete anonymise mais conserve messages : justification RGPD ?',
      'MySQL vs PostgreSQL : différences techniques réelles ?',
      'JSON statiques = NoSQL ? Quand une vraie base NoSQL ?',
      '4 variantes de toDTO() : restructuration polymorphe ?',
      'Pourquoi 200 OK même si email n\'existe pas ?',
    ],
    questionsCCP3: [
      'Construisez un jeu d\'essai pour le questionnaire d\'orientation',
      'docker compose down && up : impact utilisateurs ? Zéro-downtime, rollback ?',
      'Veille vulnérabilités pendant le projet ? Une CVE récente ?',
    ],
    verdict: 'Niveau technique exceptionnel pour un CDA, nettement au-dessus des attendus ; combler avant session le jeu d\'essai et le plan de tests → validation très confortable.',
  },
  {
    prenom: 'Mathew',
    nom: 'Aubert',
    projet: 'TDAppy (communauté TDA/H, 54 p.)',
    stack: 'Angular (SPA, façade, signals) / Spring Boot 3 / MySQL',
    notes: {
      CCP1: 'moyen',
      CCP2: 'bien',
      CCP3: 'moyen',
    },
    resume: 'TDAppy, app web en équipe de 4 : ressources TDA/H, forum, outils (Pomodoro, tâches), annuaire CMP. Angular, Spring Boot 3 couches, MySQL, Docker/VPS, CI/CD GitHub Actions, Traefik.',
    pointsForts: [
      'MCD + MPD complets et cohérents',
      'Justification systématique des choix techniques avec alternatives',
      'Workflow git professionnel (production/staging/development)',
      'CI/CD réelle et aboutie',
      'Front Angular de bon niveau avec justification performance',
      'Récit de veille JPA avant/après honnête',
      'Outillage qualité : husky, linters, Swagger, Compodoc, Wave',
    ],
    anglesMorts: [
      'SÉCURITÉ — angle mort majeur, éliminatoire : sections vides',
      'Veille vulnérabilités : absente',
      'Jeu d\'essai : absent',
      'Plan de tests formalisé : absent',
      'Diagramme de classes / architectures : titres vides',
      'Liste des compétences REAC : absente',
      'Script SQL : absent',
      'Anglais : aucune trace',
      'Annexes inexistantes',
    ],
    moyen_ameliorer: [
      'Tests : intégration illisible, pas de couverture',
      'Accessibilité : Wave/RGAA cités mais rien de démontré',
      'RGPD : principes listés mais non appliqués',
      'ACID incomplet, captures de l\'app réelle absentes',
      'CD : StrictHostKeyChecking=no à savoir justifier',
    ],
    questionsCCP1: [
      'Stockage des mots de passe : quel algorithme de hachage et pourquoi ?',
      'Protection injection SQL et XSS dans le forum (Quill) ?',
      'Authentification de bout en bout : où est stocké le token côté front ?',
      'Un sprint concret : tâches, reste à faire, gestion d\'un retard ?',
      'Accessibilité RGAA : deux critères réellement respectés ?',
    ],
    questionsCCP2: [
      'Données TDA/H = sensibles : obligations RGPD spécifiques ?',
      'MCD → MPD : transformation de l\'association n-n « Response_like » + script SQL ?',
      'Pourquoi un soft delete sur Users ? Conséquences et RGPD ?',
      'Dans quel cas du NoSQL dans TDAppy ?',
      'Diagramme de classes du domaine backend (absent) : relations Topic/Response/User ?',
    ],
    questionsCCP3: [
      'Jeu d\'essai de la fonctionnalité la plus représentative (à préparer impérativement)',
      'StrictHostKeyChecking=no + secret SSH : risques, durcissement, rollback ?',
    ],
    verdict: 'Socle technique réel et prometteur (BDD, front, CI/CD), mais dossier en brouillon avec la sécurité quasi absente : NON RECEVABLE en l\'état, validable après finalisation sérieuse.',
    alerte: 'Dossier en BROUILLON : nombreuses sections vides, placeholders',
  },
  {
    prenom: 'Mawele',
    nom: 'Mbizi Biniakounou',
    projet: 'Jokeur (santé animale, 99 p.)',
    stack: 'Angular 21 (Signals, standalone, SSR) / Spring Boot 4 / MySQL',
    notes: {
      CCP1: 'excellent',
      CCP2: 'bien',
      CCP3: 'bien (proche d\'excellent)',
    },
    resume: 'Joker, équipe de 4, 8 sprits : carnet de santé animal (mesures, vaccins, traitements, rappels, RDV). Angular 21 SSR / Spring Boot 4 / MySQL, VPS OVH, Docker, Traefik, CI/CD. RGPD/RGAA/RGESN couverts.',
    pointsForts: [
      'Wireframes + maquettes, responsive avec tableau de breakpoints',
      'Code Angular moderne réel, pattern Strategy illustré',
      'POO/SOLID appliqués au projet',
      'Backlog MoSCoW, Git 4 branches, Husky/Checkstyle',
      'Architecture multicouche justifiée, comparatifs solides',
      'Merise complet, JPA/JPQL/DTO/Mapper, GlobalExceptionHandler',
      'Sécurité très complète : SecurityFilterChain/JwtFilter réels, RBAC, BCrypt',
      'DevOps professionnel : CI séquencée, Testcontainers',
      'Front Angular moderne (Signals, computed, Strategy)',
      'Justifications systématiques avec alternatives écartées',
      'RGPD/RGAA/RGESN + CGU/LCEN, Swagger désactivé en prod',
      'Backlog réel, rituels, Daily',
    ],
    anglesMorts: [
      'NoSQL absent en mise en œuvre',
      'Script SQL de création : non fourni',
      'Veille vulnérabilités : générique, aucune CVE/outil/faille corrigée',
      'Jeu d\'essai avec analyse des écarts : absent',
      'Plan de tests en tant que document : absent',
      'Anglais : aucune trace',
      'Planning/suivi des écarts : non démontré',
      '99 pages : hors gabarit REAC (40-60)',
      'Contraintes/livrables du MVP non formalisés',
      'Sauvegarde/restauration MySQL : rien',
    ],
    moyen_ameliorer: [
      'Use cases simplistes et incohérents',
      'Diagramme de classes pivoté/divergent',
      'Cohérence Merise (measure.health_record_number, notification sans FK)',
      'Section 13 négligée — contraste suspect avec le reste',
      'Numérotation dupliquée, images en double, annexes identiques',
      'Test Jest vs Java : contrat à clarifier',
      'Rate limiting Traefik ET Spring : qui fait quoi ?',
      'Purge automatique après inactivité RGPD : à prouver',
    ],
    questionsCCP1: [
      'JWT en LocalStorage vs HttpOnly : pourquoi ; gestion du refresh token ?',
      'Test unitaire d\'un composant Angular avec Signals : montrez',
      'User stories « Non commencé » : gestion des écarts ?',
      'Test Jest false vs exception Java : contrat réel ?',
      'Un exemple vécu où Husky/Checkstyle a bloqué un commit ?',
    ],
    questionsCCP2: [
      'Un cas où MongoDB ou Redis aurait été pertinent + structure d\'un document',
      'Script SQL ? Création/migration en prod (Flyway/Liquibase ?) ?',
      'measure.health_record_number et notification sans FK : expliquez',
      '« Add animal weight » extends « Create notebook » : justifiez',
      'GET /measures/{healthRecordId}/{type} : contrôle d\'appartenance (IDOR) ?',
    ],
    questionsCCP3: [
      'Plan de tests formel + jeu d\'essai avec un écart analysé',
      'Veille sécurité : une CVE/advisory détectée sur vos dépendances ?',
      '« Zero-Downtime » vs docker compose down && up : contradiction ?',
      'Comment le front est-il testé/déployé en CI ? Si E2E échouent ?',
    ],
    verdict: 'Niveau technique nettement supérieur aux attendus (sécurité, DevOps, architecture) ; validation probable sous réserve de démontrer une maîtrise personnelle réelle et de combler NoSQL, script SQL, plan de tests, veille, format.',
    alerte: '99 pages : dépasse le gabarit REAC (40-60 p.)',
  },
  {
    prenom: 'Sara',
    nom: 'Kadimi',
    projet: 'Jokeur + Showcase CNAV (87 p.)',
    stack: 'Angular 21 SSR / Spring Boot 4 / MySQL',
    notes: {
      CCP1: 'excellent',
      CCP2: 'excellent',
      CCP3: 'bien',
    },
    resume: 'Deux projets : Jokeur (carnet santé animal, équipe 4, 9 semaines) et Showcase (stage CNAV : app Angular de documentation Web Components Design System Castor). Merise/UML/Figma, fil rouge « gestion des symptômes » complet, tests 3 niveaux, CI/CD, multi-environnements.',
    pointsForts: [
      'Double projet équilibré (groupe + entreprise) couvrant toutes les compétences',
      'Fil rouge « gestion des symptômes » suivi de bout en bout',
      'Modélisation complète et propre Merise + UML (classes, séquence, activité)',
      'Résolutions de problèmes authentiques : CastorInputDirective, ViewContainerRef, parsing RSS ROME',
      'Choix justifiés en tableaux comparatifs',
      'Infra pro : 4 environnements compose, CI/CD complet',
      'Honnêteté sur les limites + glossaire complet',
      'Maquettes Figma, responsive/RGAA, interfaces dynamiques',
      'ValidationPipe, GlobalExceptionHandler, Scrum 9 semaines',
      'Sécurité honnête (JWT/BCrypt, CORS)',
      'User stories MoSCoW, use cases, script SQL (annexe 14.2)',
      'Tests 3 niveaux avec code',
    ],
    anglesMorts: [
      'Veille vulnérabilités : porte sur les Signals, pas la sécurité ; OWASP/CVE absents',
      'Jeu d\'essai : absent',
      'Plan de tests formalisé : chap. 7 = cours, pas un plan',
      'NoSQL : zéro mention',
      'Anglais : README seulement',
      'Cahier des charges non présenté',
      'Pas de Gantt ni analyse des écarts',
      'Éco-conception en 4 lignes',
    ],
    moyen_ameliorer: [
      'SecurityConfig incohérent : /api/symptoms/** exige ADMIN vs utilisateur ajoute symptômes',
      'AuthGuard SSR : return true hors navigateur',
      'RGPD et RGAA déclaratifs',
      'Coquilles : « DBInitializr », « appoitment », type « LOGICAL »',
      '~87 p. : dépasse gabarit 40-60',
      'Aucun chiffre de couverture de tests',
      'Showcase : peu de preuves personnelles',
    ],
    questionsCCP1: [
      '/api/symptoms/** réservé ADMIN vs use case utilisateur : qui peut faire quoi ?',
      'JWT en localStorage : mesures compensatoires ? Version cookie HttpOnly ?',
      'Veille sécurité : sources, une vulnérabilité OWASP Top 10, une faille corrigée ?',
      'AuthGuard retourne true côté SSR : non-authentifié peut-il voir contenu privé ?',
    ],
    questionsCCP2: [
      'Pourquoi SymptomHealthRecordEntity explicite plutôt que @ManyToMany ?',
      'MPD avec type « LOGICAL » et « appoitment » : ce script a-t-il tourné ?',
      'Un cas NoSQL dans Jokeur ; différences de modélisation ?',
      'Validation Rules front + Jakarta DTO + Rules back : duplication ?',
    ],
    questionsCCP3: [
      'Jeu d\'essai « ajout de symptôme » : entrées, attendu, obtenu, écart analysé',
      'Plan de tests couvre-t-il tout le backlog ? Taux de couverture ?',
      'docker compose down && up : indisponibilité ? Migration sans casser prod ?',
      'Restauration de la base en cas d\'incident VPS ?',
    ],
    verdict: 'Techniquement riche et largement au-dessus des attendus (conception, architecture, déploiement), mais exposé à des questions sévères sur la veille sécurité, le jeu d\'essai, le NoSQL — admissible « très bon » si la soutenance comble ces trous.',
    alerte: '~87 pages : dépasse le gabarit REAC (40-60 p.)',
  },
  {
    prenom: 'Yolain',
    nom: 'Hoarau',
    projet: 'Jokeur (suivi santé animal)',
    stack: 'Angular SSR/Tailwind / Spring Boot + Spring Security/JWT / MySQL',
    notes: {
      CCP1: 'bien (proche d\'excellent)',
      CCP2: 'bien',
      CCP3: 'bien',
    },
    resume: 'Jokeur, équipe de 4 (01-03/2026) : carnets de santé animaux, mesures, vaccins, rappels. Front Angular SSR/Tailwind, API Spring Boot, MySQL, Docker/Traefik sur VPS, CI/CD GitHub Actions. Authentification complète (inscription, connexion, reset, suppression RGPD). 20 annexes, staging en ligne.',
    pointsForts: [
      'Environnement très complet',
      'Interfaces avec validations/responsive/accessibilité aria',
      'POO/SOLID avec code réel',
      'Trello 7 sprits',
      'User stories/MVP clairs, architecture en couches bien expliquée',
      'MCD/MLD/SQL solides',
      '125 tests unitaires + intégration + Cypress E2E',
      'Jeu d\'essai au format REAC',
      'CI/CD réels, Docker multi-stage, Traefik/Let\'s Encrypt',
      'Chaîne DevOps complète et prouvée',
      'Sécurité auth bien conçue : BCrypt, token reset SHA-256, anti-IDOR',
      'Tableau d\'analyse de risques (injection, XSS, CSRF)',
      'RGPD traité concrètement',
      'Honnêteté remarquable : limites explicitées partout',
      'Staging en ligne',
    ],
    anglesMorts: [
      'Maquettes et enchaînement : attendu REAC explicite, absents',
      'NoSQL : aucune mention',
      'Veille vulnérabilités : veille générale seulement, pas OWASP/CVE/ANSSI',
      'Anglais : aucune section B1 valorisée',
      'Pas de planning prévisionnel vs réalisé',
      'Éco-conception effleurée',
      'Pas de tests de sécurité automatisés',
    ],
    moyen_ameliorer: [
      'Validation côté serveur non systématique',
      'JWT en localStorage, alternative cookie HttpOnly non discutée',
      'Tests back suppression de compte manquants',
      'Fichiers photo_key non supprimés',
      '380 warnings ESLint non traités',
      'Types SQL discutables',
      'Brute force non protégé',
    ],
    questionsCCP1: [
      'JWT en localStorage : risque principal ? Alternative ? Impact cookie HttpOnly sur CSRF ?',
      'POST /auth/register via Postman avec mot de passe « a » : que se passe-t-il ?',
      'Comment implémenter une protection brute force dans Spring Security ?',
      'Exemple concret de violation SOLID dans Jokeur et refactoring ?',
      'Gestion des conflits/revue de code à 4 ? Un retard de sprint ?',
    ],
    questionsCCP2: [
      'Où sont vos wireframes ? Démarche de maquettage de l\'équipe ?',
      'Quelle donnée aurait justifié du NoSQL et pourquoi ? Garanties vs MySQL ?',
      'DECIMAL(4,2) : poids max stockable ? Migration sans perte ?',
      'Table « presents » vs « symptom_health_record » : redondance ?',
      'CascadeType.ALL + orphanRemoval : risques ? SQL généré vérifié ?',
    ],
    questionsCCP3: [
      'Veille spécifique vulnérabilités (sources, fréquence) ? Une CVE récente ?',
      'docker compose down/up : conséquence utilisateurs ? Procédure rollback ?',
    ],
    verdict: 'Dossier solide, honnête et bien prouvé, au niveau attendu du titre avec un CCP3 convaincant ; validation probable sous réserve de compenser à l\'oral : maquettes, NoSQL, veille sécurité, validation serveur.',
  },
]
